apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: widera-testing
spec:
  deletionPolicy: Delete
  forProvider:
    chart:
      name: Forgejo
      repository: "oci://code.forgejo.org/forgejo-helm/forgejo"
      version: 11.0.1
      url: "oci://code.forgejo.org/forgejo-helm/forgejo:11.0.1"
    namespace: widera-testing
    values:
      gitea:
        startupProbe:
          enabled: false
        readinessProbe:
          enabled: false
        config:
          APP_NAME: Yolo Forgejo
          database:
            DB_TYPE: sqlite3
            SCHEMA: public
      postgresql:
        enabled: false
      postgresql-ha:
        enabled: false
      redis:
        enabled: false
      redis-cluster:
        enabled: false
  managementPolicies:
  - '*'
  providerConfigRef:
    name: helm
  writeConnectionSecretToRef:
    name: from-hand-connection
    namespace: widera-testing
