//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppCat) DeepCopyInto(out *AppCat) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.Details != nil {
		in, out := &in.Details, &out.Details
		*out = make(Details, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Plans != nil {
		in, out := &in.Plans, &out.Plans
		*out = make(map[string]VSHNPlan, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppCat.
func (in *AppCat) DeepCopy() *AppCat {
	if in == nil {
		return nil
	}
	out := new(AppCat)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AppCat) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppCatList) DeepCopyInto(out *AppCatList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AppCat, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppCatList.
func (in *AppCatList) DeepCopy() *AppCatList {
	if in == nil {
		return nil
	}
	out := new(AppCatList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AppCatList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppCatStatus) DeepCopyInto(out *AppCatStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppCatStatus.
func (in *AppCatStatus) DeepCopy() *AppCatStatus {
	if in == nil {
		return nil
	}
	out := new(AppCatStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in Details) DeepCopyInto(out *Details) {
	{
		in := &in
		*out = make(Details, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Details.
func (in Details) DeepCopy() Details {
	if in == nil {
		return nil
	}
	out := new(Details)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SGBackupInfo) DeepCopyInto(out *SGBackupInfo) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Process.DeepCopyInto(&out.Process)
	in.BackupInformation.DeepCopyInto(&out.BackupInformation)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SGBackupInfo.
func (in *SGBackupInfo) DeepCopy() *SGBackupInfo {
	if in == nil {
		return nil
	}
	out := new(SGBackupInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VSHNMariaDBBackup) DeepCopyInto(out *VSHNMariaDBBackup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VSHNMariaDBBackup.
func (in *VSHNMariaDBBackup) DeepCopy() *VSHNMariaDBBackup {
	if in == nil {
		return nil
	}
	out := new(VSHNMariaDBBackup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VSHNMariaDBBackup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VSHNMariaDBBackupList) DeepCopyInto(out *VSHNMariaDBBackupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VSHNMariaDBBackup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VSHNMariaDBBackupList.
func (in *VSHNMariaDBBackupList) DeepCopy() *VSHNMariaDBBackupList {
	if in == nil {
		return nil
	}
	out := new(VSHNMariaDBBackupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VSHNMariaDBBackupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VSHNMariaDBBackupStatus) DeepCopyInto(out *VSHNMariaDBBackupStatus) {
	*out = *in
	in.Date.DeepCopyInto(&out.Date)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VSHNMariaDBBackupStatus.
func (in *VSHNMariaDBBackupStatus) DeepCopy() *VSHNMariaDBBackupStatus {
	if in == nil {
		return nil
	}
	out := new(VSHNMariaDBBackupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VSHNPlan) DeepCopyInto(out *VSHNPlan) {
	*out = *in
	out.JSize = in.JSize
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VSHNPlan.
func (in *VSHNPlan) DeepCopy() *VSHNPlan {
	if in == nil {
		return nil
	}
	out := new(VSHNPlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VSHNPostgresBackup) DeepCopyInto(out *VSHNPostgresBackup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VSHNPostgresBackup.
func (in *VSHNPostgresBackup) DeepCopy() *VSHNPostgresBackup {
	if in == nil {
		return nil
	}
	out := new(VSHNPostgresBackup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VSHNPostgresBackup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VSHNPostgresBackupList) DeepCopyInto(out *VSHNPostgresBackupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VSHNPostgresBackup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VSHNPostgresBackupList.
func (in *VSHNPostgresBackupList) DeepCopy() *VSHNPostgresBackupList {
	if in == nil {
		return nil
	}
	out := new(VSHNPostgresBackupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VSHNPostgresBackupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VSHNPostgresBackupStatus) DeepCopyInto(out *VSHNPostgresBackupStatus) {
	*out = *in
	if in.Process != nil {
		in, out := &in.Process, &out.Process
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.BackupInformation != nil {
		in, out := &in.BackupInformation, &out.BackupInformation
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VSHNPostgresBackupStatus.
func (in *VSHNPostgresBackupStatus) DeepCopy() *VSHNPostgresBackupStatus {
	if in == nil {
		return nil
	}
	out := new(VSHNPostgresBackupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VSHNRedisBackup) DeepCopyInto(out *VSHNRedisBackup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VSHNRedisBackup.
func (in *VSHNRedisBackup) DeepCopy() *VSHNRedisBackup {
	if in == nil {
		return nil
	}
	out := new(VSHNRedisBackup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VSHNRedisBackup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VSHNRedisBackupList) DeepCopyInto(out *VSHNRedisBackupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VSHNRedisBackup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VSHNRedisBackupList.
func (in *VSHNRedisBackupList) DeepCopy() *VSHNRedisBackupList {
	if in == nil {
		return nil
	}
	out := new(VSHNRedisBackupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VSHNRedisBackupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VSHNRedisBackupStatus) DeepCopyInto(out *VSHNRedisBackupStatus) {
	*out = *in
	in.Date.DeepCopyInto(&out.Date)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VSHNRedisBackupStatus.
func (in *VSHNRedisBackupStatus) DeepCopy() *VSHNRedisBackupStatus {
	if in == nil {
		return nil
	}
	out := new(VSHNRedisBackupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VSHNSize) DeepCopyInto(out *VSHNSize) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VSHNSize.
func (in *VSHNSize) DeepCopy() *VSHNSize {
	if in == nil {
		return nil
	}
	out := new(VSHNSize)
	in.DeepCopyInto(out)
	return out
}
