//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package codey

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Codey) DeepCopyInto(out *Codey) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Codey.
func (in *Codey) DeepCopy() *Codey {
	if in == nil {
		return nil
	}
	out := new(Codey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Codey) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeyList) DeepCopyInto(out *CodeyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Codey, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeyList.
func (in *CodeyList) DeepCopy() *CodeyList {
	if in == nil {
		return nil
	}
	out := new(CodeyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CodeyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeyParameters) DeepCopyInto(out *CodeyParameters) {
	*out = *in
	in.Service.DeepCopyInto(&out.Service)
	out.Size = in.Size
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeyParameters.
func (in *CodeyParameters) DeepCopy() *CodeyParameters {
	if in == nil {
		return nil
	}
	out := new(CodeyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeyServiceSpec) DeepCopyInto(out *CodeyServiceSpec) {
	*out = *in
	if in.FQDN != nil {
		in, out := &in.FQDN, &out.FQDN
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeyServiceSpec.
func (in *CodeyServiceSpec) DeepCopy() *CodeyServiceSpec {
	if in == nil {
		return nil
	}
	out := new(CodeyServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeySpec) DeepCopyInto(out *CodeySpec) {
	*out = *in
	in.Parameters.DeepCopyInto(&out.Parameters)
	out.WriteConnectionSecretToRef = in.WriteConnectionSecretToRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeySpec.
func (in *CodeySpec) DeepCopy() *CodeySpec {
	if in == nil {
		return nil
	}
	out := new(CodeySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeyStatus) DeepCopyInto(out *CodeyStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeyStatus.
func (in *CodeyStatus) DeepCopy() *CodeyStatus {
	if in == nil {
		return nil
	}
	out := new(CodeyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VSHNCodeySizeSpec) DeepCopyInto(out *VSHNCodeySizeSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VSHNCodeySizeSpec.
func (in *VSHNCodeySizeSpec) DeepCopy() *VSHNCodeySizeSpec {
	if in == nil {
		return nil
	}
	out := new(VSHNCodeySizeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XCodey) DeepCopyInto(out *XCodey) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XCodey.
func (in *XCodey) DeepCopy() *XCodey {
	if in == nil {
		return nil
	}
	out := new(XCodey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *XCodey) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XCodeyList) DeepCopyInto(out *XCodeyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]XCodey, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XCodeyList.
func (in *XCodeyList) DeepCopy() *XCodeyList {
	if in == nil {
		return nil
	}
	out := new(XCodeyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *XCodeyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XCodeySpec) DeepCopyInto(out *XCodeySpec) {
	*out = *in
	in.Parameters.DeepCopyInto(&out.Parameters)
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XCodeySpec.
func (in *XCodeySpec) DeepCopy() *XCodeySpec {
	if in == nil {
		return nil
	}
	out := new(XCodeySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XCodeyStatus) DeepCopyInto(out *XCodeyStatus) {
	*out = *in
	out.CodeyStatus = in.CodeyStatus
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XCodeyStatus.
func (in *XCodeyStatus) DeepCopy() *XCodeyStatus {
	if in == nil {
		return nil
	}
	out := new(XCodeyStatus)
	in.DeepCopyInto(out)
	return out
}
