apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: '10'
  labels:
    name: kubernetes
  name: kubernetes
spec:
  controllerConfigRef:
    name: kubernetes
  package: docker.io/crossplane/provider-kubernetes:v0.4.0
---
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: '10'
  labels:
    name: kubernetes
  name: kubernetes
spec:
  serviceAccountName: provider-kubernetes
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations: {}
  labels:
    name: provider-kubernetes
  name: provider-kubernetes
  namespace: syn-crossplane
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations: {}
  labels:
    name: crossplane-provider-provider-kubernetes-system-custom
  name: crossplane:provider:provider-kubernetes:system:custom
rules:
  - apiGroups:
      - kubernetes.crossplane.io
    resources:
      - '*'
    verbs:
      - get
      - list
      - watch
      - update
      - patch
      - create
      - delete
  - apiGroups:
      - ''
      - coordination.k8s.io
    resources:
      - secrets
      - configmaps
      - events
      - leases
    verbs:
      - '*'
  - apiGroups:
      - ''
    resources:
      - namespaces
    verbs:
      - get
      - list
      - watch
      - create
      - watch
      - patch
      - update
      - delete
  - apiGroups:
      - stackgres.io
    resources:
      - sginstanceprofiles
      - sgclusters
      - sgpgconfigs
      - sgobjectstorages
    verbs:
      - get
      - list
      - watch
      - update
      - patch
      - create
      - delete
  - apiGroups:
      - networking.k8s.io
    resources:
      - networkpolicies
    verbs:
      - get
      - list
      - watch
      - update
      - patch
      - create
      - delete
  - apiGroups:
      - appcat.vshn.io
    resources:
      - xobjectbuckets
    verbs:
      - get
      - list
      - watch
      - update
      - patch
      - create
      - delete
  - apiGroups:
      - cert-manager.io
    resources:
      - issuers
      - certificates
    verbs:
      - get
      - list
      - watch
      - update
      - patch
      - create
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations: {}
  labels:
    name: crossplane-provider-provider-kubernetes-system-custom
  name: crossplane:provider:provider-kubernetes:system:custom
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crossplane:provider:provider-kubernetes:system:custom
subjects:
  - kind: ServiceAccount
    name: provider-kubernetes
    namespace: syn-crossplane
