apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: '10'
  labels:
    name: xobjectbuckets.appcat.vshn.io
  name: xobjectbuckets.appcat.vshn.io
spec:
  claimNames:
    kind: ObjectBucket
    plural: objectbuckets
  connectionSecretKeys:
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - AWS_REGION
    - ENDPOINT
    - ENDPOINT_URL
    - BUCKET_NAME
  defaultCompositionRef:
    name: dev.objectbuckets.appcat.vshn.io
  group: appcat.vshn.io
  names:
    kind: XObjectBucket
    plural: xobjectbuckets
  versions:
    - additionalPrinterColumns:
        - jsonPath: .spec.parameters.bucketName
          name: Bucket Name
          type: string
        - jsonPath: .spec.parameters.region
          name: Region
          type: string
      name: v1
      referenceable: true
      schema:
        openAPIV3Schema:
          description: ObjectBucket is the API for creating S3 buckets.
          properties:
            spec:
              description: ObjectBucketSpec defines the desired state of a ObjectBucket.
              properties:
                parameters:
                  description: ObjectBucketParameters are the configurable fields
                    of a ObjectBucket.
                  properties:
                    bucketName:
                      description: BucketName is the name of the bucket to create.
                        Cannot be changed after bucket is created. Name must be acceptable
                        by the S3 protocol, which follows RFC 1123. Be aware that
                        S3 providers may require a unique name across the platform
                        or region.
                      type: string
                    region:
                      description: Region is the name of the region where the bucket
                        shall be created. The region must be available in the S3 endpoint.
                      type: string
                  required:
                    - bucketName
                    - region
                  type: object
              type: object
            status:
              description: ObjectBucketStatus reflects the observed state of a ObjectBucket.
              properties:
                accessUserConditions:
                  description: AccessUserConditions contains a copy of the claim's
                    underlying user account conditions.
                  items:
                    properties:
                      lastTransitionTime:
                        description: LastTransitionTime is the last time the condition
                          transitioned from one status to another.
                        format: date-time
                        type: string
                      message:
                        description: Message is a human-readable message indicating
                          details about the transition.
                        maxLength: 32768
                        type: string
                      observedGeneration:
                        description: ObservedGeneration represents the .metadata.generation
                          that the condition was set based upon. For instance, if
                          .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration
                          is 9, the condition is out of date with respect to the current
                          state of the instance.
                        format: int64
                        minimum: 0
                        type: integer
                      reason:
                        description: Reason contains a programmatic identifier indicating
                          the reason for the condition's last transition.
                        maxLength: 1024
                        pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
                        type: string
                      status:
                        description: Status of the condition, one of True, False,
                          Unknown.
                        enum:
                          - 'True'
                          - 'False'
                          - Unknown
                        type: string
                      type:
                        description: Type of condition.
                        maxLength: 316
                        pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$
                        type: string
                    type: object
                  type: array
                bucketConditions:
                  description: BucketConditions contains a copy of the claim's underlying
                    bucket conditions.
                  items:
                    properties:
                      lastTransitionTime:
                        description: LastTransitionTime is the last time the condition
                          transitioned from one status to another.
                        format: date-time
                        type: string
                      message:
                        description: Message is a human-readable message indicating
                          details about the transition.
                        maxLength: 32768
                        type: string
                      observedGeneration:
                        description: ObservedGeneration represents the .metadata.generation
                          that the condition was set based upon. For instance, if
                          .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration
                          is 9, the condition is out of date with respect to the current
                          state of the instance.
                        format: int64
                        minimum: 0
                        type: integer
                      reason:
                        description: Reason contains a programmatic identifier indicating
                          the reason for the condition's last transition.
                        maxLength: 1024
                        pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
                        type: string
                      status:
                        description: Status of the condition, one of True, False,
                          Unknown.
                        enum:
                          - 'True'
                          - 'False'
                          - Unknown
                        type: string
                      type:
                        description: Type of condition.
                        maxLength: 316
                        pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$
                        type: string
                    type: object
                  type: array
              type: object
          required:
            - spec
          type: object
      served: true
