apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: '10'
    metadata.appcat.vshn.io/description: Redis DBaaS instances by Exoscale
    metadata.appcat.vshn.io/displayname: Exoscale Redis
    metadata.appcat.vshn.io/end-user-docs-url: https://docs.appuio.cloud/appcat/exoscale-dbaas/redis/create.html
    metadata.appcat.vshn.io/product-description: https://products.docs.vshn.ch/products/appcat/exoscale_dbaas.html
    metadata.appcat.vshn.io/zone: 'Exoscale zones: de-fra-1, de-muc-1, at-vie-1, ch-gva-2,
      ch-dk-2, bg-sof-1'
  labels:
    metadata.appcat.vshn.io/offered: 'false'
    metadata.appcat.vshn.io/serviceID: exoscale-redis
    name: exoscaleredis.exoscale.appcat.vshn.io
  name: exoscaleredis.exoscale.appcat.vshn.io
spec:
  compositeTypeRef:
    apiVersion: exoscale.appcat.vshn.io/v1
    kind: XExoscaleRedis
  patchSets:
    - name: annotations
      patches:
        - fromFieldPath: metadata.annotations
          toFieldPath: metadata.annotations
          type: FromCompositeFieldPath
    - name: labels
      patches:
        - fromFieldPath: metadata.labels
          toFieldPath: metadata.labels
          type: FromCompositeFieldPath
  resources:
    - base:
        apiVersion: exoscale.crossplane.io/v1
        kind: Redis
        metadata: {}
        spec:
          forProvider:
            ipFilter: ''
            maintenance:
              dayOfWeek: ''
              timeOfDay: ''
            redisSettings: {}
            size:
              plan: ''
            terminationProtection: false
            zone: ''
          providerConfigRef:
            name: exoscale
          writeConnectionSecretToRef:
            name: ''
            namespace: syn-provider-exoscale-secrets
      connectionDetails:
        - fromConnectionSecretKey: REDIS_HOST
          name: REDIS_HOST
          type: FromConnectionSecretKey
        - fromConnectionSecretKey: REDIS_PORT
          name: REDIS_PORT
          type: FromConnectionSecretKey
        - fromConnectionSecretKey: REDIS_USERNAME
          name: REDIS_USERNAME
          type: FromConnectionSecretKey
        - fromConnectionSecretKey: REDIS_PASSWORD
          name: REDIS_PASSWORD
          type: FromConnectionSecretKey
        - fromConnectionSecretKey: REDIS_URL
          name: REDIS_URL
          type: FromConnectionSecretKey
      patches:
        - patchSetName: annotations
          type: PatchSet
        - patchSetName: labels
          type: PatchSet
        - fromFieldPath: metadata.labels[crossplane.io/composite]
          toFieldPath: metadata.name
          type: FromCompositeFieldPath
        - fromFieldPath: metadata.labels[crossplane.io/composite]
          toFieldPath: spec.writeConnectionSecretToRef.name
          type: FromCompositeFieldPath
        - fromFieldPath: spec.parameters.service.redisSettings
          toFieldPath: spec.forProvider.redisSettings
          type: FromCompositeFieldPath
        - fromFieldPath: spec.parameters.service.zone
          toFieldPath: spec.forProvider.zone
          type: FromCompositeFieldPath
        - fromFieldPath: spec.parameters.network.ipFilter
          toFieldPath: spec.forProvider.ipFilter
          type: FromCompositeFieldPath
        - fromFieldPath: spec.parameters.size.plan
          toFieldPath: spec.forProvider.size.plan
          type: FromCompositeFieldPath
        - fromFieldPath: spec.parameters.maintenance.dayOfWeek
          toFieldPath: spec.forProvider.maintenance.dayOfWeek
          type: FromCompositeFieldPath
        - fromFieldPath: spec.parameters.maintenance.timeOfDay
          toFieldPath: spec.forProvider.maintenance.timeOfDay
          type: FromCompositeFieldPath
  writeConnectionSecretsToNamespace: syn-crossplane
