---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appcat-sli-exporter
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - garage.rajsingh.info
  resources:
  - garagebuckets
  - garagekeys
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - managedupgrade.appuio.io
  resources:
  - upgradejobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vshn.appcat.vshn.io
  resources:
  - vshngarages
  - vshnmariadbs
  - vshnminios
  - vshnpostgresqls
  - vshnredis
  - xvshngarages
  - xvshnkeycloaks
  - xvshnmariadbs
  - xvshnminios
  - xvshnpostgresqls
  - xvshnredis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vshn.appcat.vshn.io
  resources:
  - vshngarages/status
  - vshnmariadbs/status
  - vshnminios/status
  - vshnpostgresqls/status
  - vshnredis/status
  - xvshngarages/status
  - xvshnkeycloaks/status
  - xvshnmariadbs/status
  - xvshnminios/status
  - xvshnpostgresqls/status
  - xvshnredis/status
  verbs:
  - get
