// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.1 DO NOT EDIT.
package v1

// SGDbOpsSpec defines model for SGDbOpsSpec.
type SGDbOpsSpec struct {
	// Configuration of the benchmark
	Benchmark *SGDbOpsSpecBenchmark `json:"benchmark,omitempty"`

	// Configuration of major version upgrade (see also [`pg_upgrade`](https://www.postgresql.org/docs/current/pgupgrade.html) command)
	MajorVersionUpgrade *SGDbOpsSpecMajorVersionUpgrade `json:"majorVersionUpgrade,omitempty"`

	// The maximum number of retries the operation is allowed to do after a failure.
	//
	// A value of `0` (zero) means no retries are made. Defaults to: `0`.
	MaxRetries *int `json:"maxRetries,omitempty"`

	// Configuration of minor version upgrade
	MinorVersionUpgrade *SGDbOpsSpecMinorVersionUpgrade `json:"minorVersionUpgrade,omitempty"`

	// The kind of operation that will be performed on the SGCluster. Available operations are:
	//
	// * `benchmark`: run a benchmark on the specified SGCluster and report the results in the status.
	// * `vacuum`: perform a [vacuum](https://www.postgresql.org/docs/current/sql-vacuum.html) operation on the specified SGCluster.
	// * `repack`: run [`pg_repack`](https://github.com/reorg/pg_repack) command on the specified SGCluster.
	// * `majorVersionUpgrade`: perform a major version upgrade of PostgreSQL using [`pg_upgrade`](https://www.postgresql.org/docs/current/pgupgrade.html) command.
	// * `restart`: perform a restart of the cluster.
	// * `minorVersionUpgrade`: perform a minor version upgrade of PostgreSQL.
	// * `securityUpgrade`: perform a security upgrade of the cluster.
	Op string `json:"op"`

	// Configuration of [`pg_repack`](https://github.com/reorg/pg_repack) command
	Repack *SGDbOpsSpecRepack `json:"repack,omitempty"`

	// Configuration of restart
	Restart *SGDbOpsSpecRestart `json:"restart,omitempty"`

	// An ISO 8601 date, that holds UTC scheduled date of the operation execution.
	//
	// If not specified or if the date it's in the past, it will be interpreted ASAP.
	RunAt *string `json:"runAt,omitempty"`

	// Pod custom node scheduling and affinity configuration
	Scheduling *SGDbOpsSpecScheduling `json:"scheduling,omitempty"`

	// Configuration of security upgrade
	SecurityUpgrade *SGDbOpsSpecSecurityUpgrade `json:"securityUpgrade,omitempty"`

	// The name of SGCluster on which the operation will be performed.
	SgCluster string `json:"sgCluster"`

	// An ISO 8601 duration in the format `PnDTnHnMn.nS`, that specifies a timeout after which the operation execution will be canceled.
	//
	// If the operation can not be performed due to timeout expiration, the condition `Failed` will have a status of `True` and the reason will be `OperationTimedOut`.
	//
	// If not specified the operation will never fail for timeout expiration.
	Timeout *string `json:"timeout,omitempty"`

	// Configuration of [vacuum](https://www.postgresql.org/docs/current/sql-vacuum.html) operation
	Vacuum *SGDbOpsSpecVacuum `json:"vacuum,omitempty"`
}

// SGDbOpsSpecBenchmark defines model for SGDbOpsSpecBenchmark.
type SGDbOpsSpecBenchmark struct {
	// Specify the service where the benchmark will connect to:
	//
	// * `primary-service`: Connect to the primary service
	// * `replicas-service`: Connect to the replicas service
	ConnectionType *string `json:"connectionType,omitempty"`

	// The credentials of the user that will be used by the benchmark
	Credentials *SGDbOpsSpecBenchmarkCredentials `json:"credentials,omitempty"`

	// When specified will indicate the database where the benchmark will run upon.
	//
	// If not specified a target database with a random name will be created and removed after the benchmark completes.
	Database *string `json:"database,omitempty"`

	// Configuration of [pgbench](https://www.postgresql.org/docs/current/pgbench.html) benchmark
	Pgbench *SGDbOpsSpecBenchmarkPgbench `json:"pgbench,omitempty"`

	// Configuration of sampling benchmark.
	Sampling *SGDbOpsSpecBenchmarkSampling `json:"sampling,omitempty"`

	// The type of benchmark that will be performed on the SGCluster. Available benchmarks are:
	//
	// * `pgbench`: run [pgbench](https://www.postgresql.org/docs/current/pgbench.html) on the specified SGCluster and report the results in the status.
	// * `sampling`: samples real queries and store them in the SGDbOps status in order to be used by a `pgbench` benchmark using `replay` mode.
	Type string `json:"type"`
}

// SGDbOpsSpecBenchmarkCredentials defines model for SGDbOpsSpecBenchmarkCredentials.
type SGDbOpsSpecBenchmarkCredentials struct {
	// The password that will be used by the benchmark
	//
	// If not specified the default superuser password will be used.
	Password SGDbOpsSpecBenchmarkCredentialsPassword `json:"password"`

	// The username that will be used by the benchmark.
	//
	// If not specified the default superuser username (by default postgres) will be used.
	Username SGDbOpsSpecBenchmarkCredentialsUsername `json:"username"`
}

// SGDbOpsSpecBenchmarkCredentialsPassword defines model for SGDbOpsSpecBenchmarkCredentialsPassword.
type SGDbOpsSpecBenchmarkCredentialsPassword struct {
	// The Secret key where the password is stored.
	Key string `json:"key"`

	// The Secret name where the password is stored.
	Name string `json:"name"`
}

// SGDbOpsSpecBenchmarkCredentialsUsername defines model for SGDbOpsSpecBenchmarkCredentialsUsername.
type SGDbOpsSpecBenchmarkCredentialsUsername struct {
	// The Secret key where the username is stored.
	Key string `json:"key"`

	// The Secret name where the username is stored.
	Name string `json:"name"`
}

// SGDbOpsSpecBenchmarkPgbench defines model for SGDbOpsSpecBenchmarkPgbench.
type SGDbOpsSpecBenchmarkPgbench struct {
	// Number of clients simulated, that is, number of concurrent database sessions. Defaults to: `1`.
	ConcurrentClients *int `json:"concurrentClients,omitempty"`

	// This section allow to configure custom SQL for initialization and scripts used by pgbench.
	Custom *SGDbOpsSpecBenchmarkPgbenchCustom `json:"custom,omitempty"`

	// Size of the database to generate. This size is specified either in Mebibytes, Gibibytes or Tebibytes (multiples of 2^20, 2^30 or 2^40, respectively).
	DatabaseSize string `json:"databaseSize"`

	// An ISO 8601 duration in the format `PnDTnHnMn.nS`, that specifies how long the benchmark will run.
	Duration string `json:"duration"`

	// Create the pgbench_accounts, pgbench_tellers and pgbench_branches tables with the given fillfactor. Default is 100.
	Fillfactor *int `json:"fillfactor,omitempty"`

	// Create foreign key constraints between the standard tables. (This option only take effect if `custom.initiailization` is not specified).
	ForeignKeys *bool `json:"foreignKeys,omitempty"`

	// Perform just a selected set of the normal initialization steps. init_steps specifies the initialization steps to be performed, using one character per step. Each step is invoked in the specified order. The default is dtgvp. The available steps are:
	//
	// * `d` (Drop): Drop any existing pgbench tables.
	// * `t` (create Tables): Create the tables used by the standard pgbench scenario, namely pgbench_accounts, pgbench_branches, pgbench_history, and pgbench_tellers.
	// * `g` or `G` (Generate data, client-side or server-side): Generate data and load it into the standard tables, replacing any data already present.
	//   With `g` (client-side data generation), data is generated in pgbench client and then sent to the server. This uses the client/server bandwidth extensively through a COPY. pgbench uses the FREEZE option with version 14 or later of PostgreSQL to speed up subsequent VACUUM, unless partitions are enabled. Using g causes logging to print one message every 100,000 rows while generating data for the pgbench_accounts table.
	//   With `G` (server-side data generation), only small queries are sent from the pgbench client and then data is actually generated in the server. No significant bandwidth is required for this variant, but the server will do more work. Using G causes logging not to print any progress message while generating data.
	//   The default initialization behavior uses client-side data generation (equivalent to g).
	// * `v` (Vacuum): Invoke VACUUM on the standard tables.
	// * `p` (create Primary keys): Create primary key indexes on the standard tables.
	// * `f` (create Foreign keys): Create foreign key constraints between the standard tables. (Note that this step is not performed by default.)
	InitSteps *string `json:"initSteps,omitempty"`

	// The pgbench benchmark type:
	//
	// * `tpcb-like`: The benchmark is inspired by the [TPC-B benchmark](https://www.tpc.org/TPC_Documents_Latest_Versions/TPC-B_v2.0.0.pdf). It is the default mode when `connectionType` is set to `primary-service`.
	// * `select-only`: The `tpcb-like` but only using SELECTs commands. It is the default mode when `connectionType` is set to `replicas-service`.
	// * `custom`: will use the scripts in the `custom` section to initialize and and run commands for the benchmark.
	// * `replay`: will replay the sampled queries of a sampling benchmark SGDbOps. If the `custom` section is specified it will be used instead. Queries can be referenced setting `custom.scripts.replay` to the index of the query in the sampling benchmark SGDbOps's status (index start from 0).
	//
	// See also https://www.postgresql.org/docs/current/pgbench.html#TRANSACTIONS-AND-SCRIPTS
	Mode *string `json:"mode,omitempty"`

	// Perform no vacuuming during initialization. (This option suppresses the `v` initialization step, even if it was specified in `initSteps`.)
	NoVacuum *bool `json:"noVacuum,omitempty"`

	// Create a partitioned pgbench_accounts table with the specified method. Expected values are `range` or `hash`. This option requires that partitions is set to non-zero. If unspecified, default is `range`. (This option only take effect if `custom.initiailization` is not specified).
	PartitionMethod *string `json:"partitionMethod,omitempty"`

	// Create a partitioned pgbench_accounts table with the specified number of partitions of nearly equal size for the scaled number of accounts. Default is 0, meaning no partitioning. (This option only take effect if `custom.initiailization` is not specified).
	Partitions *int `json:"partitions,omitempty"`

	// Protocol to use for submitting queries to the server:
	//
	// * `simple`: use simple query protocol.
	// * `extended`: use extended query protocol.
	// * `prepared`: use extended query protocol with prepared statements.
	//
	// In the prepared mode, pgbench reuses the parse analysis result starting from the second query iteration, so pgbench runs faster than in other modes.
	//
	// The default is `simple` query protocol. See also https://www.postgresql.org/docs/current/protocol.html
	QueryMode *string `json:"queryMode,omitempty"`

	// Sampling rate, used when collecting data, to reduce the amount of collected data. If this option is given, only the specified fraction of transactions are collected. 1.0 means all transactions will be logged, 0.05 means only 5% of the transactions will be logged.
	SamplingRate *float32 `json:"samplingRate,omitempty"`

	// benchmark SGDbOps of type sampling that will be used to replay sampled queries.
	SamplingSGDbOps *string `json:"samplingSGDbOps,omitempty"`

	// Number of worker threads within pgbench. Using more than one thread can be helpful on multi-CPU machines. Clients are distributed as evenly as possible among available threads. Default is `1`.
	Threads *int `json:"threads,omitempty"`

	// Create all tables as unlogged tables, rather than permanent tables. (This option only take effect if `custom.initiailization` is not specified).
	UnloggedTables *bool `json:"unloggedTables,omitempty"`

	// **Deprecated** this field is ignored, use `queryMode` instead.
	//
	// Use extended query protocol with prepared statements. Defaults to: `false`.
	UsePreparedStatements *bool `json:"usePreparedStatements,omitempty"`
}

// SGDbOpsSpecBenchmarkPgbenchCustom defines model for SGDbOpsSpecBenchmarkPgbenchCustom.
type SGDbOpsSpecBenchmarkPgbenchCustom struct {
	// The custom SQL for initialization that will be executed in place of pgbench default initialization.
	//
	// If not specified the default pgbench initialization will be performed instead.
	Initialization *SGDbOpsSpecBenchmarkPgbenchCustomInitialization `json:"initialization,omitempty"`

	// The custom SQL scripts that will be executed by pgbench during the benchmark instead of default pgbench scripts
	Scripts *[]SGDbOpsSpecBenchmarkPgbenchCustomScriptsItem `json:"scripts,omitempty"`
}

// SGDbOpsSpecBenchmarkPgbenchCustomInitialization defines model for SGDbOpsSpecBenchmarkPgbenchCustomInitialization.
type SGDbOpsSpecBenchmarkPgbenchCustomInitialization struct {
	// Raw SQL script to execute. This field is mutually exclusive with `scriptFrom` field.
	Script *string `json:"script,omitempty"`

	// Reference to either a Kubernetes [Secret](https://kubernetes.io/docs/concepts/configuration/secret/) or a [ConfigMap](https://kubernetes.io/docs/concepts/configuration/configmap/) that contains the SQL script to execute. This field is mutually exclusive with `script` field.
	//
	// Fields `secretKeyRef` and `configMapKeyRef` are mutually exclusive, and one of them is required.
	ScriptFrom *SGDbOpsSpecBenchmarkPgbenchCustomInitializationScriptFrom `json:"scriptFrom,omitempty"`
}

// SGDbOpsSpecBenchmarkPgbenchCustomInitializationScriptFrom defines model for SGDbOpsSpecBenchmarkPgbenchCustomInitializationScriptFrom.
type SGDbOpsSpecBenchmarkPgbenchCustomInitializationScriptFrom struct {
	// A [ConfigMap](https://kubernetes.io/docs/concepts/configuration/configmap/) reference that contains the SQL script to execute. This field is mutually exclusive with `secretKeyRef` field.
	ConfigMapKeyRef *SGDbOpsSpecBenchmarkPgbenchCustomInitializationScriptFromConfigMapKeyRef `json:"configMapKeyRef,omitempty"`

	// A Kubernetes [SecretKeySelector](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.29/#secretkeyselector-v1-core) that contains the SQL script to execute. This field is mutually exclusive with `configMapKeyRef` field.
	SecretKeyRef *SGDbOpsSpecBenchmarkPgbenchCustomInitializationScriptFromSecretKeyRef `json:"secretKeyRef,omitempty"`
}

// SGDbOpsSpecBenchmarkPgbenchCustomInitializationScriptFromConfigMapKeyRef defines model for SGDbOpsSpecBenchmarkPgbenchCustomInitializationScriptFromConfigMapKeyRef.
type SGDbOpsSpecBenchmarkPgbenchCustomInitializationScriptFromConfigMapKeyRef struct {
	// The key name within the ConfigMap that contains the SQL script to execute.
	Key *string `json:"key,omitempty"`

	// The name of the ConfigMap that contains the SQL script to execute.
	Name *string `json:"name,omitempty"`
}

// SGDbOpsSpecBenchmarkPgbenchCustomInitializationScriptFromSecretKeyRef defines model for SGDbOpsSpecBenchmarkPgbenchCustomInitializationScriptFromSecretKeyRef.
type SGDbOpsSpecBenchmarkPgbenchCustomInitializationScriptFromSecretKeyRef struct {
	// The key of the secret to select from. Must be a valid secret key.
	Key *string `json:"key,omitempty"`

	// Name of the referent. [More information](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names).
	Name *string `json:"name,omitempty"`
}

// SGDbOpsSpecBenchmarkPgbenchCustomScriptsItem defines model for SGDbOpsSpecBenchmarkPgbenchCustomScriptsItem.
type SGDbOpsSpecBenchmarkPgbenchCustomScriptsItem struct {
	// The name of the builtin script to use. See https://www.postgresql.org/docs/current/pgbench.html#PGBENCH-OPTION-BUILTIN
	//
	// When specified fields `replay`, `script` and `scriptFrom` must not be set.
	Builtin *string `json:"builtin,omitempty"`

	// The index of the query in the sampling benchmark SGDbOps's status (index start from 0).
	//
	// When specified fields `builtin`, `script` and `scriptFrom` must not be set.
	Replay *int `json:"replay,omitempty"`

	// Raw SQL script to execute. This field is mutually exclusive with `scriptFrom` field.
	Script *string `json:"script,omitempty"`

	// Reference to either a Kubernetes [Secret](https://kubernetes.io/docs/concepts/configuration/secret/) or a [ConfigMap](https://kubernetes.io/docs/concepts/configuration/configmap/) that contains the SQL script to execute. This field is mutually exclusive with `script` field.
	//
	// Fields `secretKeyRef` and `configMapKeyRef` are mutually exclusive, and one of them is required.
	ScriptFrom *SGDbOpsSpecBenchmarkPgbenchCustomScriptsItemScriptFrom `json:"scriptFrom,omitempty"`

	// The weight of this custom SQL script.
	Weight *int `json:"weight,omitempty"`
}

// SGDbOpsSpecBenchmarkPgbenchCustomScriptsItemScriptFrom defines model for SGDbOpsSpecBenchmarkPgbenchCustomScriptsItemScriptFrom.
type SGDbOpsSpecBenchmarkPgbenchCustomScriptsItemScriptFrom struct {
	// A [ConfigMap](https://kubernetes.io/docs/concepts/configuration/configmap/) reference that contains the SQL script to execute. This field is mutually exclusive with `secretKeyRef` field.
	ConfigMapKeyRef *SGDbOpsSpecBenchmarkPgbenchCustomScriptsItemScriptFromConfigMapKeyRef `json:"configMapKeyRef,omitempty"`

	// A Kubernetes [SecretKeySelector](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.29/#secretkeyselector-v1-core) that contains the SQL script to execute. This field is mutually exclusive with `configMapKeyRef` field.
	SecretKeyRef *SGDbOpsSpecBenchmarkPgbenchCustomScriptsItemScriptFromSecretKeyRef `json:"secretKeyRef,omitempty"`
}

// SGDbOpsSpecBenchmarkPgbenchCustomScriptsItemScriptFromConfigMapKeyRef defines model for SGDbOpsSpecBenchmarkPgbenchCustomScriptsItemScriptFromConfigMapKeyRef.
type SGDbOpsSpecBenchmarkPgbenchCustomScriptsItemScriptFromConfigMapKeyRef struct {
	// The key name within the ConfigMap that contains the SQL script to execute.
	Key *string `json:"key,omitempty"`

	// The name of the ConfigMap that contains the SQL script to execute.
	Name *string `json:"name,omitempty"`
}

// SGDbOpsSpecBenchmarkPgbenchCustomScriptsItemScriptFromSecretKeyRef defines model for SGDbOpsSpecBenchmarkPgbenchCustomScriptsItemScriptFromSecretKeyRef.
type SGDbOpsSpecBenchmarkPgbenchCustomScriptsItemScriptFromSecretKeyRef struct {
	// The key of the secret to select from. Must be a valid secret key.
	Key *string `json:"key,omitempty"`

	// Name of the referent. [More information](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names).
	Name *string `json:"name,omitempty"`
}

// SGDbOpsSpecBenchmarkSampling defines model for SGDbOpsSpecBenchmarkSampling.
type SGDbOpsSpecBenchmarkSampling struct {
	// The query used to select top queries. Will be ignored if `mode` is not set to `custom`.
	//
	// The query must return at most 2 columns:
	//
	// * First column returned by the query must be a column holding the query identifier, also available in pg_stat_activity (column `query_id`) and pg_stat_statements (column `queryid`).
	// * Second column is optional and, if returned, must hold a json object containing only text keys and values stat will be used to generate the stats.
	//
	// See also:
	//
	// * https://www.postgresql.org/docs/current/monitoring-stats.html#MONITORING-PG-STAT-ACTIVITY-VIEW
	// * https://www.postgresql.org/docs/current/pgstatstatements.html#PGSTATSTATEMENTS-PG-STAT-STATEMENTS
	CustomTopQueriesQuery *string `json:"customTopQueriesQuery,omitempty"`

	// The mode used to select the top queries used for sampling:
	//
	// * `time`: The top queries will be selected among the most slow queries.
	// * `calls`: The top queries will be selected among the most called queries.
	// * `custom`: The `customTopQueriesQuery` will be used to select top queries.
	Mode *string `json:"mode,omitempty"`

	// When `true` omit to include the top queries stats in the SGDbOps status. By default `false`.
	OmitTopQueriesInStatus *bool `json:"omitTopQueriesInStatus,omitempty"`

	// Number of sampled queries to include in the result. By default `10`.
	Queries *int `json:"queries,omitempty"`

	// An ISO 8601 duration in the format `PnDTnHnMn.nS`, that specifies how long will last the sampling of real queries that will be replayed later.
	SamplingDuration string `json:"samplingDuration"`

	// Minimum number of microseconds the sampler will wait between each sample is taken. By default `10000` (10 milliseconds).
	SamplingMinInterval *int `json:"samplingMinInterval,omitempty"`

	// The target database to be sampled. By default `postgres`.
	//
	// The benchmark database will be used to store the sampled queries but user must specify a target database to be sampled in the `sampling` section.
	TargetDatabase string `json:"targetDatabase"`

	// An ISO 8601 duration in the format `PnDTnHnMn.nS`, that specifies how long the to wait before selecting top queries in order to collect enough stats.
	TopQueriesCollectDuration string `json:"topQueriesCollectDuration"`

	// Regular expression for filtering representative statements when selecting top queries. Will be ignored if `mode` is set to `custom`. By default is `^ *(with|select) `. See https://www.postgresql.org/docs/current/functions-matching.html#FUNCTIONS-POSIX-REGEXP
	TopQueriesFilter *string `json:"topQueriesFilter,omitempty"`

	// Minimum number of queries to consider as part of the top queries. By default `5`.
	TopQueriesMin *int `json:"topQueriesMin,omitempty"`

	// Percentile of queries to consider as part of the top queries. Will be ignored if `mode` is set to `custom`. By default `95`.
	TopQueriesPercentile *int `json:"topQueriesPercentile,omitempty"`
}

// SGDbOpsSpecMajorVersionUpgrade defines model for SGDbOpsSpecMajorVersionUpgrade.
type SGDbOpsSpecMajorVersionUpgrade struct {
	// The path were the backup is stored. If not set this field is filled up by the operator.
	//
	// When provided will indicate were the backups and WAL files will be stored.
	//
	// The path should be different from the current `.spec.configurations.backups[].path` value for the target `SGCluster`
	//   in order to avoid mixing WAL files of two distinct major versions of postgres.
	BackupPath *string `json:"backupPath,omitempty"`

	// If true does some checks to see if the cluster can perform a major version upgrade without changing any data. Defaults to: `false`.
	Check *bool `json:"check,omitempty"`

	// If true use efficient file cloning (also known as "reflinks" on some systems) instead of copying files to the new cluster.
	// This can result in near-instantaneous copying of the data files, giving the speed advantages of `link` while leaving the old
	//   cluster untouched. This option is mutually exclusive with `link`. Defaults to: `false`.
	//
	// File cloning is only supported on some operating systems and file systems. If it is selected but not supported, the pg_upgrade
	//   run will error. At present, it is supported on Linux (kernel 4.5 or later) with Btrfs and XFS (on file systems created with
	//   reflink support), and on macOS with APFS.
	Clone *bool `json:"clone,omitempty"`

	// If true use hard links instead of copying files to the new cluster. This option is mutually exclusive with `clone`. Defaults to: `false`.
	Link *bool `json:"link,omitempty"`

	// A major version upgrade can not be performed if a required extension is not present for the target major version of the upgrade.
	// In those cases you will have to provide the target extension version of the extension for the target major version of postgres.
	// Beware that in some cases it is not possible to upgrade an extension alongside postgres. This is the case for PostGIS or timescaledb.
	//  In such cases you will have to upgrade the extension before or after the major version upgrade. Please make sure you read the
	//  documentation of each extension in order to understand if it is possible to upgrade it during a major version upgrade of postgres.
	PostgresExtensions *[]SGDbOpsSpecMajorVersionUpgradePostgresExtensionsItem `json:"postgresExtensions,omitempty"`

	// The target postgres version that must have the same major version of the target SGCluster.
	PostgresVersion *string `json:"postgresVersion,omitempty"`

	// The postgres config that must have the same major version of the target postgres version.
	SgPostgresConfig *string `json:"sgPostgresConfig,omitempty"`

	// The list of Postgres extensions to install.
	//
	// **This section is filled by the operator.**
	ToInstallPostgresExtensions *[]SGDbOpsSpecMajorVersionUpgradeToInstallPostgresExtensionsItem `json:"toInstallPostgresExtensions,omitempty"`
}

// SGDbOpsSpecMajorVersionUpgradePostgresExtensionsItem defines model for SGDbOpsSpecMajorVersionUpgradePostgresExtensionsItem.
type SGDbOpsSpecMajorVersionUpgradePostgresExtensionsItem struct {
	// The name of the extension to deploy.
	Name string `json:"name"`

	// The id of the publisher of the extension to deploy. If not specified `com.ongres` will be used by default.
	Publisher *string `json:"publisher,omitempty"`

	// The repository base URL from where to obtain the extension to deploy.
	//
	// **This section is filled by the operator.**
	Repository *string `json:"repository,omitempty"`

	// The version of the extension to deploy. If not specified version of `stable` channel will be used by default and if only a version is available that one will be used.
	Version *string `json:"version,omitempty"`
}

// SGDbOpsSpecMajorVersionUpgradeToInstallPostgresExtensionsItem defines model for SGDbOpsSpecMajorVersionUpgradeToInstallPostgresExtensionsItem.
type SGDbOpsSpecMajorVersionUpgradeToInstallPostgresExtensionsItem struct {
	// The build version of the extension to install.
	Build *string `json:"build,omitempty"`

	// The extra mounts of the extension to install.
	ExtraMounts *[]string `json:"extraMounts,omitempty"`

	// The name of the extension to install.
	Name string `json:"name"`

	// The postgres major version of the extension to install.
	PostgresVersion string `json:"postgresVersion"`

	// The id of the publisher of the extension to install.
	Publisher string `json:"publisher"`

	// The repository base URL from where the extension will be installed from.
	Repository string `json:"repository"`

	// The version of the extension to install.
	Version string `json:"version"`
}

// SGDbOpsSpecMinorVersionUpgrade defines model for SGDbOpsSpecMinorVersionUpgrade.
type SGDbOpsSpecMinorVersionUpgrade struct {
	// The method used to perform the minor version upgrade operation. Available methods are:
	//
	// * `InPlace`: the in-place method does not require more resources than those that are available.
	//   In case only an instance of the StackGres cluster is present this mean the service disruption will
	//   last longer so we encourage use the reduced impact restart and especially for a production environment.
	// * `ReducedImpact`: this procedure is the same as the in-place method but require additional
	//   resources in order to spawn a new updated replica that will be removed when the procedure completes.
	Method *string `json:"method,omitempty"`

	// The target postgres version that must have the same major version of the target SGCluster.
	PostgresVersion *string `json:"postgresVersion,omitempty"`
}

// SGDbOpsSpecRepack defines model for SGDbOpsSpecRepack.
type SGDbOpsSpecRepack struct {
	// List of database to vacuum or repack, don't specify to select all databases
	Databases *[]SGDbOpsSpecRepackDatabasesItem `json:"databases,omitempty"`

	// If true don't repack tables which belong to specific extension. Defaults to: `false`.
	ExcludeExtension *bool `json:"excludeExtension,omitempty"`

	// If true don't analyze at end. Defaults to: `false`.
	NoAnalyze *bool `json:"noAnalyze,omitempty"`

	// If true don't kill other backends when timed out. Defaults to: `false`.
	NoKillBackend *bool `json:"noKillBackend,omitempty"`

	// If true do vacuum full instead of cluster. Defaults to: `false`.
	NoOrder *bool `json:"noOrder,omitempty"`

	// If specified, an ISO 8601 duration format `PnDTnHnMn.nS` to set a timeout to cancel other backends on conflict.
	WaitTimeout *string `json:"waitTimeout,omitempty"`
}

// SGDbOpsSpecRepackDatabasesItem defines model for SGDbOpsSpecRepackDatabasesItem.
type SGDbOpsSpecRepackDatabasesItem struct {
	// If true don't repack tables which belong to specific extension. Defaults to: `false`.
	ExcludeExtension *bool `json:"excludeExtension,omitempty"`

	// the name of the database
	Name string `json:"name"`

	// If true don't analyze at end. Defaults to: `false`.
	NoAnalyze *bool `json:"noAnalyze,omitempty"`

	// If true don't kill other backends when timed out. Defaults to: `false`.
	NoKillBackend *bool `json:"noKillBackend,omitempty"`

	// If true do vacuum full instead of cluster. Defaults to: `false`.
	NoOrder *bool `json:"noOrder,omitempty"`

	// If specified, an ISO 8601 duration format `PnDTnHnMn.nS` to set a timeout to cancel other backends on conflict.
	WaitTimeout *string `json:"waitTimeout,omitempty"`
}

// SGDbOpsSpecRestart defines model for SGDbOpsSpecRestart.
type SGDbOpsSpecRestart struct {
	// The method used to perform the restart operation. Available methods are:
	//
	// * `InPlace`: the in-place method does not require more resources than those that are available.
	//   In case only an instance of the StackGres cluster is present this mean the service disruption will
	//   last longer so we encourage use the reduced impact restart and especially for a production environment.
	// * `ReducedImpact`: this procedure is the same as the in-place method but require additional
	//   resources in order to spawn a new updated replica that will be removed when the procedure completes.
	Method *string `json:"method,omitempty"`

	// By default all Pods are restarted. Setting this option to `true` allow to restart only those Pods which
	//   are in pending restart state as detected by the operation. Defaults to: `false`.
	OnlyPendingRestart *bool `json:"onlyPendingRestart,omitempty"`
}

// SGDbOpsSpecScheduling defines model for SGDbOpsSpecScheduling.
type SGDbOpsSpecScheduling struct {
	// Node affinity is a group of node affinity scheduling rules.
	//
	// See https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.29/#nodeaffinity-v1-core
	NodeAffinity *SGDbOpsSpecSchedulingNodeAffinity `json:"nodeAffinity,omitempty"`

	// NodeSelector is a selector which must be true for the pod to fit on a node. Selector which must match a node's labels for the pod to be scheduled on that node. More info: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
	NodeSelector map[string]string `json:"nodeSelector,omitempty"`

	// Pod affinity is a group of inter pod affinity scheduling rules.
	//
	// See https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.29/#podaffinity-v1-core
	PodAffinity *SGDbOpsSpecSchedulingPodAffinity `json:"podAffinity,omitempty"`

	// Pod anti affinity is a group of inter pod anti affinity scheduling rules.
	//
	// See https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.29/#podantiaffinity-v1-core
	PodAntiAffinity *SGDbOpsSpecSchedulingPodAntiAffinity `json:"podAntiAffinity,omitempty"`

	// If specified, indicates the pod's priority. "system-node-critical" and "system-cluster-critical" are two special keywords which indicate the highest priorities with the former being the highest priority. Any other name must be defined by creating a PriorityClass object with that name. If not specified, the pod priority will be default or zero if there is no default.
	PriorityClassName *string `json:"priorityClassName,omitempty"`

	// If specified, the pod's tolerations.
	//
	// See https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.29/#toleration-v1-core
	Tolerations *[]SGDbOpsSpecSchedulingTolerationsItem `json:"tolerations,omitempty"`
}

// SGDbOpsSpecSchedulingNodeAffinity defines model for SGDbOpsSpecSchedulingNodeAffinity.
type SGDbOpsSpecSchedulingNodeAffinity struct {
	// The scheduler will prefer to schedule pods to nodes that satisfy the affinity expressions specified by this field, but it may choose a node that violates one or more of the expressions. The node that is most preferred is the one with the greatest sum of weights, i.e. for each node that meets all of the scheduling requirements (resource request, requiredDuringScheduling affinity expressions, etc.), compute a sum by iterating through the elements of this field and adding "weight" to the sum if the node matches the corresponding matchExpressions; the node(s) with the highest sum are the most preferred.
	PreferredDuringSchedulingIgnoredDuringExecution *[]SGDbOpsSpecSchedulingNodeAffinityPreferredDuringSchedulingIgnoredDuringExecutionItem `json:"preferredDuringSchedulingIgnoredDuringExecution,omitempty"`

	// A node selector represents the union of the results of one or more label queries over a set of nodes; that is, it represents the OR of the selectors represented by the node selector terms.
	RequiredDuringSchedulingIgnoredDuringExecution *SGDbOpsSpecSchedulingNodeAffinityRequiredDuringSchedulingIgnoredDuringExecution `json:"requiredDuringSchedulingIgnoredDuringExecution,omitempty"`
}

// SGDbOpsSpecSchedulingNodeAffinityPreferredDuringSchedulingIgnoredDuringExecutionItem defines model for SGDbOpsSpecSchedulingNodeAffinityPreferredDuringSchedulingIgnoredDuringExecutionItem.
type SGDbOpsSpecSchedulingNodeAffinityPreferredDuringSchedulingIgnoredDuringExecutionItem struct {
	// A null or empty node selector term matches no objects. The requirements of them are ANDed. The TopologySelectorTerm type implements a subset of the NodeSelectorTerm.
	Preference SGDbOpsSpecSchedulingNodeAffinityPreferredDuringSchedulingIgnoredDuringExecutionItemPreference `json:"preference"`

	// Weight associated with matching the corresponding nodeSelectorTerm, in the range 1-100.
	Weight int32 `json:"weight"`
}

// SGDbOpsSpecSchedulingNodeAffinityPreferredDuringSchedulingIgnoredDuringExecutionItemPreference defines model for SGDbOpsSpecSchedulingNodeAffinityPreferredDuringSchedulingIgnoredDuringExecutionItemPreference.
type SGDbOpsSpecSchedulingNodeAffinityPreferredDuringSchedulingIgnoredDuringExecutionItemPreference struct {
	// A list of node selector requirements by node's labels.
	MatchExpressions *[]SGDbOpsSpecSchedulingNodeAffinityPreferredDuringSchedulingIgnoredDuringExecutionItemPreferenceMatchExpressionsItem `json:"matchExpressions,omitempty"`

	// A list of node selector requirements by node's fields.
	MatchFields *[]SGDbOpsSpecSchedulingNodeAffinityPreferredDuringSchedulingIgnoredDuringExecutionItemPreferenceMatchFieldsItem `json:"matchFields,omitempty"`
}

// SGDbOpsSpecSchedulingNodeAffinityPreferredDuringSchedulingIgnoredDuringExecutionItemPreferenceMatchExpressionsItem defines model for SGDbOpsSpecSchedulingNodeAffinityPreferredDuringSchedulingIgnoredDuringExecutionItemPreferenceMatchExpressionsItem.
type SGDbOpsSpecSchedulingNodeAffinityPreferredDuringSchedulingIgnoredDuringExecutionItemPreferenceMatchExpressionsItem struct {
	// The label key that the selector applies to.
	Key string `json:"key"`

	// Represents a key's relationship to a set of values. Valid operators are In, NotIn, Exists, DoesNotExist. Gt, and Lt.
	Operator string `json:"operator"`

	// An array of string values. If the operator is In or NotIn, the values array must be non-empty. If the operator is Exists or DoesNotExist, the values array must be empty. If the operator is Gt or Lt, the values array must have a single element, which will be interpreted as an integer. This array is replaced during a strategic merge patch.
	Values *[]string `json:"values,omitempty"`
}

// SGDbOpsSpecSchedulingNodeAffinityPreferredDuringSchedulingIgnoredDuringExecutionItemPreferenceMatchFieldsItem defines model for SGDbOpsSpecSchedulingNodeAffinityPreferredDuringSchedulingIgnoredDuringExecutionItemPreferenceMatchFieldsItem.
type SGDbOpsSpecSchedulingNodeAffinityPreferredDuringSchedulingIgnoredDuringExecutionItemPreferenceMatchFieldsItem struct {
	// The label key that the selector applies to.
	Key string `json:"key"`

	// Represents a key's relationship to a set of values. Valid operators are In, NotIn, Exists, DoesNotExist. Gt, and Lt.
	Operator string `json:"operator"`

	// An array of string values. If the operator is In or NotIn, the values array must be non-empty. If the operator is Exists or DoesNotExist, the values array must be empty. If the operator is Gt or Lt, the values array must have a single element, which will be interpreted as an integer. This array is replaced during a strategic merge patch.
	Values *[]string `json:"values,omitempty"`
}

// SGDbOpsSpecSchedulingNodeAffinityRequiredDuringSchedulingIgnoredDuringExecution defines model for SGDbOpsSpecSchedulingNodeAffinityRequiredDuringSchedulingIgnoredDuringExecution.
type SGDbOpsSpecSchedulingNodeAffinityRequiredDuringSchedulingIgnoredDuringExecution struct {
	// Required. A list of node selector terms. The terms are ORed.
	NodeSelectorTerms []SGDbOpsSpecSchedulingNodeAffinityRequiredDuringSchedulingIgnoredDuringExecutionNodeSelectorTermsItem `json:"nodeSelectorTerms"`
}

// SGDbOpsSpecSchedulingNodeAffinityRequiredDuringSchedulingIgnoredDuringExecutionNodeSelectorTermsItem defines model for SGDbOpsSpecSchedulingNodeAffinityRequiredDuringSchedulingIgnoredDuringExecutionNodeSelectorTermsItem.
type SGDbOpsSpecSchedulingNodeAffinityRequiredDuringSchedulingIgnoredDuringExecutionNodeSelectorTermsItem struct {
	// A list of node selector requirements by node's labels.
	MatchExpressions *[]SGDbOpsSpecSchedulingNodeAffinityRequiredDuringSchedulingIgnoredDuringExecutionNodeSelectorTermsItemMatchExpressionsItem `json:"matchExpressions,omitempty"`

	// A list of node selector requirements by node's fields.
	MatchFields *[]SGDbOpsSpecSchedulingNodeAffinityRequiredDuringSchedulingIgnoredDuringExecutionNodeSelectorTermsItemMatchFieldsItem `json:"matchFields,omitempty"`
}

// SGDbOpsSpecSchedulingNodeAffinityRequiredDuringSchedulingIgnoredDuringExecutionNodeSelectorTermsItemMatchExpressionsItem defines model for SGDbOpsSpecSchedulingNodeAffinityRequiredDuringSchedulingIgnoredDuringExecutionNodeSelectorTermsItemMatchExpressionsItem.
type SGDbOpsSpecSchedulingNodeAffinityRequiredDuringSchedulingIgnoredDuringExecutionNodeSelectorTermsItemMatchExpressionsItem struct {
	// The label key that the selector applies to.
	Key string `json:"key"`

	// Represents a key's relationship to a set of values. Valid operators are In, NotIn, Exists, DoesNotExist. Gt, and Lt.
	Operator string `json:"operator"`

	// An array of string values. If the operator is In or NotIn, the values array must be non-empty. If the operator is Exists or DoesNotExist, the values array must be empty. If the operator is Gt or Lt, the values array must have a single element, which will be interpreted as an integer. This array is replaced during a strategic merge patch.
	Values *[]string `json:"values,omitempty"`
}

// SGDbOpsSpecSchedulingNodeAffinityRequiredDuringSchedulingIgnoredDuringExecutionNodeSelectorTermsItemMatchFieldsItem defines model for SGDbOpsSpecSchedulingNodeAffinityRequiredDuringSchedulingIgnoredDuringExecutionNodeSelectorTermsItemMatchFieldsItem.
type SGDbOpsSpecSchedulingNodeAffinityRequiredDuringSchedulingIgnoredDuringExecutionNodeSelectorTermsItemMatchFieldsItem struct {
	// The label key that the selector applies to.
	Key string `json:"key"`

	// Represents a key's relationship to a set of values. Valid operators are In, NotIn, Exists, DoesNotExist. Gt, and Lt.
	Operator string `json:"operator"`

	// An array of string values. If the operator is In or NotIn, the values array must be non-empty. If the operator is Exists or DoesNotExist, the values array must be empty. If the operator is Gt or Lt, the values array must have a single element, which will be interpreted as an integer. This array is replaced during a strategic merge patch.
	Values *[]string `json:"values,omitempty"`
}

// SGDbOpsSpecSchedulingPodAffinity defines model for SGDbOpsSpecSchedulingPodAffinity.
type SGDbOpsSpecSchedulingPodAffinity struct {
	// The scheduler will prefer to schedule pods to nodes that satisfy the affinity expressions specified by this field, but it may choose a node that violates one or more of the expressions. The node that is most preferred is the one with the greatest sum of weights, i.e. for each node that meets all of the scheduling requirements (resource request, requiredDuringScheduling affinity expressions, etc.), compute a sum by iterating through the elements of this field and adding "weight" to the sum if the node has pods which matches the corresponding podAffinityTerm; the node(s) with the highest sum are the most preferred.
	PreferredDuringSchedulingIgnoredDuringExecution *[]SGDbOpsSpecSchedulingPodAffinityPreferredDuringSchedulingIgnoredDuringExecutionItem `json:"preferredDuringSchedulingIgnoredDuringExecution,omitempty"`

	// If the affinity requirements specified by this field are not met at scheduling time, the pod will not be scheduled onto the node. If the affinity requirements specified by this field cease to be met at some point during pod execution (e.g. due to a pod label update), the system may or may not try to eventually evict the pod from its node. When there are multiple elements, the lists of nodes corresponding to each podAffinityTerm are intersected, i.e. all terms must be satisfied.
	RequiredDuringSchedulingIgnoredDuringExecution *[]SGDbOpsSpecSchedulingPodAffinityRequiredDuringSchedulingIgnoredDuringExecutionItem `json:"requiredDuringSchedulingIgnoredDuringExecution,omitempty"`
}

// SGDbOpsSpecSchedulingPodAffinityPreferredDuringSchedulingIgnoredDuringExecutionItem defines model for SGDbOpsSpecSchedulingPodAffinityPreferredDuringSchedulingIgnoredDuringExecutionItem.
type SGDbOpsSpecSchedulingPodAffinityPreferredDuringSchedulingIgnoredDuringExecutionItem struct {
	// Defines a set of pods (namely those matching the labelSelector relative to the given namespace(s)) that this pod should be co-located (affinity) or not co-located (anti-affinity) with, where co-located is defined as running on a node whose value of the label with key <topologyKey> matches that of any node on which a pod of the set of pods is running
	PodAffinityTerm SGDbOpsSpecSchedulingPodAffinityPreferredDuringSchedulingIgnoredDuringExecutionItemPodAffinityTerm `json:"podAffinityTerm"`

	// weight associated with matching the corresponding podAffinityTerm, in the range 1-100.
	Weight int32 `json:"weight"`
}

// SGDbOpsSpecSchedulingPodAffinityPreferredDuringSchedulingIgnoredDuringExecutionItemPodAffinityTerm defines model for SGDbOpsSpecSchedulingPodAffinityPreferredDuringSchedulingIgnoredDuringExecutionItemPodAffinityTerm.
type SGDbOpsSpecSchedulingPodAffinityPreferredDuringSchedulingIgnoredDuringExecutionItemPodAffinityTerm struct {
	// A label selector is a label query over a set of resources. The result of matchLabels and matchExpressions are ANDed. An empty label selector matches all objects. A null label selector matches no objects.
	LabelSelector *SGDbOpsSpecSchedulingPodAffinityPreferredDuringSchedulingIgnoredDuringExecutionItemPodAffinityTermLabelSelector `json:"labelSelector,omitempty"`

	// MatchLabelKeys is a set of pod label keys to select which pods will be taken into consideration. The keys are used to lookup values from the incoming pod labels, those key-value labels are merged with `LabelSelector` as `key in (value)` to select the group of existing pods which pods will be taken into consideration for the incoming pod's pod (anti) affinity. Keys that don't exist in the incoming pod labels will be ignored. The default value is empty. The same key is forbidden to exist in both MatchLabelKeys and LabelSelector. Also, MatchLabelKeys cannot be set when LabelSelector isn't set. This is an alpha field and requires enabling MatchLabelKeysInPodAffinity feature gate.
	MatchLabelKeys *[]string `json:"matchLabelKeys,omitempty"`

	// MismatchLabelKeys is a set of pod label keys to select which pods will be taken into consideration. The keys are used to lookup values from the incoming pod labels, those key-value labels are merged with `LabelSelector` as `key notin (value)` to select the group of existing pods which pods will be taken into consideration for the incoming pod's pod (anti) affinity. Keys that don't exist in the incoming pod labels will be ignored. The default value is empty. The same key is forbidden to exist in both MismatchLabelKeys and LabelSelector. Also, MismatchLabelKeys cannot be set when LabelSelector isn't set. This is an alpha field and requires enabling MatchLabelKeysInPodAffinity feature gate.
	MismatchLabelKeys *[]string `json:"mismatchLabelKeys,omitempty"`

	// A label selector is a label query over a set of resources. The result of matchLabels and matchExpressions are ANDed. An empty label selector matches all objects. A null label selector matches no objects.
	NamespaceSelector *SGDbOpsSpecSchedulingPodAffinityPreferredDuringSchedulingIgnoredDuringExecutionItemPodAffinityTermNamespaceSelector `json:"namespaceSelector,omitempty"`

	// namespaces specifies a static list of namespace names that the term applies to. The term is applied to the union of the namespaces listed in this field and the ones selected by namespaceSelector. null or empty namespaces list and null namespaceSelector means "this pod's namespace".
	Namespaces *[]string `json:"namespaces,omitempty"`

	// This pod should be co-located (affinity) or not co-located (anti-affinity) with the pods matching the labelSelector in the specified namespaces, where co-located is defined as running on a node whose value of the label with key topologyKey matches that of any node on which any of the selected pods is running. Empty topologyKey is not allowed.
	TopologyKey string `json:"topologyKey"`
}

// SGDbOpsSpecSchedulingPodAffinityPreferredDuringSchedulingIgnoredDuringExecutionItemPodAffinityTermLabelSelector defines model for SGDbOpsSpecSchedulingPodAffinityPreferredDuringSchedulingIgnoredDuringExecutionItemPodAffinityTermLabelSelector.
type SGDbOpsSpecSchedulingPodAffinityPreferredDuringSchedulingIgnoredDuringExecutionItemPodAffinityTermLabelSelector struct {
	// matchExpressions is a list of label selector requirements. The requirements are ANDed.
	MatchExpressions *[]SGDbOpsSpecSchedulingPodAffinityPreferredDuringSchedulingIgnoredDuringExecutionItemPodAffinityTermLabelSelectorMatchExpressionsItem `json:"matchExpressions,omitempty"`

	// matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels map is equivalent to an element of matchExpressions, whose key field is "key", the operator is "In", and the values array contains only "value". The requirements are ANDed.
	MatchLabels map[string]string `json:"matchLabels,omitempty"`
}

// SGDbOpsSpecSchedulingPodAffinityPreferredDuringSchedulingIgnoredDuringExecutionItemPodAffinityTermLabelSelectorMatchExpressionsItem defines model for SGDbOpsSpecSchedulingPodAffinityPreferredDuringSchedulingIgnoredDuringExecutionItemPodAffinityTermLabelSelectorMatchExpressionsItem.
type SGDbOpsSpecSchedulingPodAffinityPreferredDuringSchedulingIgnoredDuringExecutionItemPodAffinityTermLabelSelectorMatchExpressionsItem struct {
	// key is the label key that the selector applies to.
	Key string `json:"key"`

	// operator represents a key's relationship to a set of values. Valid operators are In, NotIn, Exists and DoesNotExist.
	Operator string `json:"operator"`

	// values is an array of string values. If the operator is In or NotIn, the values array must be non-empty. If the operator is Exists or DoesNotExist, the values array must be empty. This array is replaced during a strategic merge patch.
	Values *[]string `json:"values,omitempty"`
}

// SGDbOpsSpecSchedulingPodAffinityPreferredDuringSchedulingIgnoredDuringExecutionItemPodAffinityTermNamespaceSelector defines model for SGDbOpsSpecSchedulingPodAffinityPreferredDuringSchedulingIgnoredDuringExecutionItemPodAffinityTermNamespaceSelector.
type SGDbOpsSpecSchedulingPodAffinityPreferredDuringSchedulingIgnoredDuringExecutionItemPodAffinityTermNamespaceSelector struct {
	// matchExpressions is a list of label selector requirements. The requirements are ANDed.
	MatchExpressions *[]SGDbOpsSpecSchedulingPodAffinityPreferredDuringSchedulingIgnoredDuringExecutionItemPodAffinityTermNamespaceSelectorMatchExpressionsItem `json:"matchExpressions,omitempty"`

	// matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels map is equivalent to an element of matchExpressions, whose key field is "key", the operator is "In", and the values array contains only "value". The requirements are ANDed.
	MatchLabels map[string]string `json:"matchLabels,omitempty"`
}

// SGDbOpsSpecSchedulingPodAffinityPreferredDuringSchedulingIgnoredDuringExecutionItemPodAffinityTermNamespaceSelectorMatchExpressionsItem defines model for SGDbOpsSpecSchedulingPodAffinityPreferredDuringSchedulingIgnoredDuringExecutionItemPodAffinityTermNamespaceSelectorMatchExpressionsItem.
type SGDbOpsSpecSchedulingPodAffinityPreferredDuringSchedulingIgnoredDuringExecutionItemPodAffinityTermNamespaceSelectorMatchExpressionsItem struct {
	// key is the label key that the selector applies to.
	Key string `json:"key"`

	// operator represents a key's relationship to a set of values. Valid operators are In, NotIn, Exists and DoesNotExist.
	Operator string `json:"operator"`

	// values is an array of string values. If the operator is In or NotIn, the values array must be non-empty. If the operator is Exists or DoesNotExist, the values array must be empty. This array is replaced during a strategic merge patch.
	Values *[]string `json:"values,omitempty"`
}

// SGDbOpsSpecSchedulingPodAffinityRequiredDuringSchedulingIgnoredDuringExecutionItem defines model for SGDbOpsSpecSchedulingPodAffinityRequiredDuringSchedulingIgnoredDuringExecutionItem.
type SGDbOpsSpecSchedulingPodAffinityRequiredDuringSchedulingIgnoredDuringExecutionItem struct {
	// A label selector is a label query over a set of resources. The result of matchLabels and matchExpressions are ANDed. An empty label selector matches all objects. A null label selector matches no objects.
	LabelSelector *SGDbOpsSpecSchedulingPodAffinityRequiredDuringSchedulingIgnoredDuringExecutionItemLabelSelector `json:"labelSelector,omitempty"`

	// MatchLabelKeys is a set of pod label keys to select which pods will be taken into consideration. The keys are used to lookup values from the incoming pod labels, those key-value labels are merged with `LabelSelector` as `key in (value)` to select the group of existing pods which pods will be taken into consideration for the incoming pod's pod (anti) affinity. Keys that don't exist in the incoming pod labels will be ignored. The default value is empty. The same key is forbidden to exist in both MatchLabelKeys and LabelSelector. Also, MatchLabelKeys cannot be set when LabelSelector isn't set. This is an alpha field and requires enabling MatchLabelKeysInPodAffinity feature gate.
	MatchLabelKeys *[]string `json:"matchLabelKeys,omitempty"`

	// MismatchLabelKeys is a set of pod label keys to select which pods will be taken into consideration. The keys are used to lookup values from the incoming pod labels, those key-value labels are merged with `LabelSelector` as `key notin (value)` to select the group of existing pods which pods will be taken into consideration for the incoming pod's pod (anti) affinity. Keys that don't exist in the incoming pod labels will be ignored. The default value is empty. The same key is forbidden to exist in both MismatchLabelKeys and LabelSelector. Also, MismatchLabelKeys cannot be set when LabelSelector isn't set. This is an alpha field and requires enabling MatchLabelKeysInPodAffinity feature gate.
	MismatchLabelKeys *[]string `json:"mismatchLabelKeys,omitempty"`

	// A label selector is a label query over a set of resources. The result of matchLabels and matchExpressions are ANDed. An empty label selector matches all objects. A null label selector matches no objects.
	NamespaceSelector *SGDbOpsSpecSchedulingPodAffinityRequiredDuringSchedulingIgnoredDuringExecutionItemNamespaceSelector `json:"namespaceSelector,omitempty"`

	// namespaces specifies a static list of namespace names that the term applies to. The term is applied to the union of the namespaces listed in this field and the ones selected by namespaceSelector. null or empty namespaces list and null namespaceSelector means "this pod's namespace".
	Namespaces *[]string `json:"namespaces,omitempty"`

	// This pod should be co-located (affinity) or not co-located (anti-affinity) with the pods matching the labelSelector in the specified namespaces, where co-located is defined as running on a node whose value of the label with key topologyKey matches that of any node on which any of the selected pods is running. Empty topologyKey is not allowed.
	TopologyKey string `json:"topologyKey"`
}

// SGDbOpsSpecSchedulingPodAffinityRequiredDuringSchedulingIgnoredDuringExecutionItemLabelSelector defines model for SGDbOpsSpecSchedulingPodAffinityRequiredDuringSchedulingIgnoredDuringExecutionItemLabelSelector.
type SGDbOpsSpecSchedulingPodAffinityRequiredDuringSchedulingIgnoredDuringExecutionItemLabelSelector struct {
	// matchExpressions is a list of label selector requirements. The requirements are ANDed.
	MatchExpressions *[]SGDbOpsSpecSchedulingPodAffinityRequiredDuringSchedulingIgnoredDuringExecutionItemLabelSelectorMatchExpressionsItem `json:"matchExpressions,omitempty"`

	// matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels map is equivalent to an element of matchExpressions, whose key field is "key", the operator is "In", and the values array contains only "value". The requirements are ANDed.
	MatchLabels map[string]string `json:"matchLabels,omitempty"`
}

// SGDbOpsSpecSchedulingPodAffinityRequiredDuringSchedulingIgnoredDuringExecutionItemLabelSelectorMatchExpressionsItem defines model for SGDbOpsSpecSchedulingPodAffinityRequiredDuringSchedulingIgnoredDuringExecutionItemLabelSelectorMatchExpressionsItem.
type SGDbOpsSpecSchedulingPodAffinityRequiredDuringSchedulingIgnoredDuringExecutionItemLabelSelectorMatchExpressionsItem struct {
	// key is the label key that the selector applies to.
	Key string `json:"key"`

	// operator represents a key's relationship to a set of values. Valid operators are In, NotIn, Exists and DoesNotExist.
	Operator string `json:"operator"`

	// values is an array of string values. If the operator is In or NotIn, the values array must be non-empty. If the operator is Exists or DoesNotExist, the values array must be empty. This array is replaced during a strategic merge patch.
	Values *[]string `json:"values,omitempty"`
}

// SGDbOpsSpecSchedulingPodAffinityRequiredDuringSchedulingIgnoredDuringExecutionItemNamespaceSelector defines model for SGDbOpsSpecSchedulingPodAffinityRequiredDuringSchedulingIgnoredDuringExecutionItemNamespaceSelector.
type SGDbOpsSpecSchedulingPodAffinityRequiredDuringSchedulingIgnoredDuringExecutionItemNamespaceSelector struct {
	// matchExpressions is a list of label selector requirements. The requirements are ANDed.
	MatchExpressions *[]SGDbOpsSpecSchedulingPodAffinityRequiredDuringSchedulingIgnoredDuringExecutionItemNamespaceSelectorMatchExpressionsItem `json:"matchExpressions,omitempty"`

	// matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels map is equivalent to an element of matchExpressions, whose key field is "key", the operator is "In", and the values array contains only "value". The requirements are ANDed.
	MatchLabels map[string]string `json:"matchLabels,omitempty"`
}

// SGDbOpsSpecSchedulingPodAffinityRequiredDuringSchedulingIgnoredDuringExecutionItemNamespaceSelectorMatchExpressionsItem defines model for SGDbOpsSpecSchedulingPodAffinityRequiredDuringSchedulingIgnoredDuringExecutionItemNamespaceSelectorMatchExpressionsItem.
type SGDbOpsSpecSchedulingPodAffinityRequiredDuringSchedulingIgnoredDuringExecutionItemNamespaceSelectorMatchExpressionsItem struct {
	// key is the label key that the selector applies to.
	Key string `json:"key"`

	// operator represents a key's relationship to a set of values. Valid operators are In, NotIn, Exists and DoesNotExist.
	Operator string `json:"operator"`

	// values is an array of string values. If the operator is In or NotIn, the values array must be non-empty. If the operator is Exists or DoesNotExist, the values array must be empty. This array is replaced during a strategic merge patch.
	Values *[]string `json:"values,omitempty"`
}

// SGDbOpsSpecSchedulingPodAntiAffinity defines model for SGDbOpsSpecSchedulingPodAntiAffinity.
type SGDbOpsSpecSchedulingPodAntiAffinity struct {
	// The scheduler will prefer to schedule pods to nodes that satisfy the anti-affinity expressions specified by this field, but it may choose a node that violates one or more of the expressions. The node that is most preferred is the one with the greatest sum of weights, i.e. for each node that meets all of the scheduling requirements (resource request, requiredDuringScheduling anti-affinity expressions, etc.), compute a sum by iterating through the elements of this field and adding "weight" to the sum if the node has pods which matches the corresponding podAffinityTerm; the node(s) with the highest sum are the most preferred.
	PreferredDuringSchedulingIgnoredDuringExecution *[]SGDbOpsSpecSchedulingPodAntiAffinityPreferredDuringSchedulingIgnoredDuringExecutionItem `json:"preferredDuringSchedulingIgnoredDuringExecution,omitempty"`

	// If the anti-affinity requirements specified by this field are not met at scheduling time, the pod will not be scheduled onto the node. If the anti-affinity requirements specified by this field cease to be met at some point during pod execution (e.g. due to a pod label update), the system may or may not try to eventually evict the pod from its node. When there are multiple elements, the lists of nodes corresponding to each podAffinityTerm are intersected, i.e. all terms must be satisfied.
	RequiredDuringSchedulingIgnoredDuringExecution *[]SGDbOpsSpecSchedulingPodAntiAffinityRequiredDuringSchedulingIgnoredDuringExecutionItem `json:"requiredDuringSchedulingIgnoredDuringExecution,omitempty"`
}

// SGDbOpsSpecSchedulingPodAntiAffinityPreferredDuringSchedulingIgnoredDuringExecutionItem defines model for SGDbOpsSpecSchedulingPodAntiAffinityPreferredDuringSchedulingIgnoredDuringExecutionItem.
type SGDbOpsSpecSchedulingPodAntiAffinityPreferredDuringSchedulingIgnoredDuringExecutionItem struct {
	// Defines a set of pods (namely those matching the labelSelector relative to the given namespace(s)) that this pod should be co-located (affinity) or not co-located (anti-affinity) with, where co-located is defined as running on a node whose value of the label with key <topologyKey> matches that of any node on which a pod of the set of pods is running
	PodAffinityTerm SGDbOpsSpecSchedulingPodAntiAffinityPreferredDuringSchedulingIgnoredDuringExecutionItemPodAffinityTerm `json:"podAffinityTerm"`

	// weight associated with matching the corresponding podAffinityTerm, in the range 1-100.
	Weight int32 `json:"weight"`
}

// SGDbOpsSpecSchedulingPodAntiAffinityPreferredDuringSchedulingIgnoredDuringExecutionItemPodAffinityTerm defines model for SGDbOpsSpecSchedulingPodAntiAffinityPreferredDuringSchedulingIgnoredDuringExecutionItemPodAffinityTerm.
type SGDbOpsSpecSchedulingPodAntiAffinityPreferredDuringSchedulingIgnoredDuringExecutionItemPodAffinityTerm struct {
	// A label selector is a label query over a set of resources. The result of matchLabels and matchExpressions are ANDed. An empty label selector matches all objects. A null label selector matches no objects.
	LabelSelector *SGDbOpsSpecSchedulingPodAntiAffinityPreferredDuringSchedulingIgnoredDuringExecutionItemPodAffinityTermLabelSelector `json:"labelSelector,omitempty"`

	// MatchLabelKeys is a set of pod label keys to select which pods will be taken into consideration. The keys are used to lookup values from the incoming pod labels, those key-value labels are merged with `LabelSelector` as `key in (value)` to select the group of existing pods which pods will be taken into consideration for the incoming pod's pod (anti) affinity. Keys that don't exist in the incoming pod labels will be ignored. The default value is empty. The same key is forbidden to exist in both MatchLabelKeys and LabelSelector. Also, MatchLabelKeys cannot be set when LabelSelector isn't set. This is an alpha field and requires enabling MatchLabelKeysInPodAffinity feature gate.
	MatchLabelKeys *[]string `json:"matchLabelKeys,omitempty"`

	// MismatchLabelKeys is a set of pod label keys to select which pods will be taken into consideration. The keys are used to lookup values from the incoming pod labels, those key-value labels are merged with `LabelSelector` as `key notin (value)` to select the group of existing pods which pods will be taken into consideration for the incoming pod's pod (anti) affinity. Keys that don't exist in the incoming pod labels will be ignored. The default value is empty. The same key is forbidden to exist in both MismatchLabelKeys and LabelSelector. Also, MismatchLabelKeys cannot be set when LabelSelector isn't set. This is an alpha field and requires enabling MatchLabelKeysInPodAffinity feature gate.
	MismatchLabelKeys *[]string `json:"mismatchLabelKeys,omitempty"`

	// A label selector is a label query over a set of resources. The result of matchLabels and matchExpressions are ANDed. An empty label selector matches all objects. A null label selector matches no objects.
	NamespaceSelector *SGDbOpsSpecSchedulingPodAntiAffinityPreferredDuringSchedulingIgnoredDuringExecutionItemPodAffinityTermNamespaceSelector `json:"namespaceSelector,omitempty"`

	// namespaces specifies a static list of namespace names that the term applies to. The term is applied to the union of the namespaces listed in this field and the ones selected by namespaceSelector. null or empty namespaces list and null namespaceSelector means "this pod's namespace".
	Namespaces *[]string `json:"namespaces,omitempty"`

	// This pod should be co-located (affinity) or not co-located (anti-affinity) with the pods matching the labelSelector in the specified namespaces, where co-located is defined as running on a node whose value of the label with key topologyKey matches that of any node on which any of the selected pods is running. Empty topologyKey is not allowed.
	TopologyKey string `json:"topologyKey"`
}

// SGDbOpsSpecSchedulingPodAntiAffinityPreferredDuringSchedulingIgnoredDuringExecutionItemPodAffinityTermLabelSelector defines model for SGDbOpsSpecSchedulingPodAntiAffinityPreferredDuringSchedulingIgnoredDuringExecutionItemPodAffinityTermLabelSelector.
type SGDbOpsSpecSchedulingPodAntiAffinityPreferredDuringSchedulingIgnoredDuringExecutionItemPodAffinityTermLabelSelector struct {
	// matchExpressions is a list of label selector requirements. The requirements are ANDed.
	MatchExpressions *[]SGDbOpsSpecSchedulingPodAntiAffinityPreferredDuringSchedulingIgnoredDuringExecutionItemPodAffinityTermLabelSelectorMatchExpressionsItem `json:"matchExpressions,omitempty"`

	// matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels map is equivalent to an element of matchExpressions, whose key field is "key", the operator is "In", and the values array contains only "value". The requirements are ANDed.
	MatchLabels map[string]string `json:"matchLabels,omitempty"`
}

// SGDbOpsSpecSchedulingPodAntiAffinityPreferredDuringSchedulingIgnoredDuringExecutionItemPodAffinityTermLabelSelectorMatchExpressionsItem defines model for SGDbOpsSpecSchedulingPodAntiAffinityPreferredDuringSchedulingIgnoredDuringExecutionItemPodAffinityTermLabelSelectorMatchExpressionsItem.
type SGDbOpsSpecSchedulingPodAntiAffinityPreferredDuringSchedulingIgnoredDuringExecutionItemPodAffinityTermLabelSelectorMatchExpressionsItem struct {
	// key is the label key that the selector applies to.
	Key string `json:"key"`

	// operator represents a key's relationship to a set of values. Valid operators are In, NotIn, Exists and DoesNotExist.
	Operator string `json:"operator"`

	// values is an array of string values. If the operator is In or NotIn, the values array must be non-empty. If the operator is Exists or DoesNotExist, the values array must be empty. This array is replaced during a strategic merge patch.
	Values *[]string `json:"values,omitempty"`
}

// SGDbOpsSpecSchedulingPodAntiAffinityPreferredDuringSchedulingIgnoredDuringExecutionItemPodAffinityTermNamespaceSelector defines model for SGDbOpsSpecSchedulingPodAntiAffinityPreferredDuringSchedulingIgnoredDuringExecutionItemPodAffinityTermNamespaceSelector.
type SGDbOpsSpecSchedulingPodAntiAffinityPreferredDuringSchedulingIgnoredDuringExecutionItemPodAffinityTermNamespaceSelector struct {
	// matchExpressions is a list of label selector requirements. The requirements are ANDed.
	MatchExpressions *[]SGDbOpsSpecSchedulingPodAntiAffinityPreferredDuringSchedulingIgnoredDuringExecutionItemPodAffinityTermNamespaceSelectorMatchExpressionsItem `json:"matchExpressions,omitempty"`

	// matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels map is equivalent to an element of matchExpressions, whose key field is "key", the operator is "In", and the values array contains only "value". The requirements are ANDed.
	MatchLabels map[string]string `json:"matchLabels,omitempty"`
}

// SGDbOpsSpecSchedulingPodAntiAffinityPreferredDuringSchedulingIgnoredDuringExecutionItemPodAffinityTermNamespaceSelectorMatchExpressionsItem defines model for SGDbOpsSpecSchedulingPodAntiAffinityPreferredDuringSchedulingIgnoredDuringExecutionItemPodAffinityTermNamespaceSelectorMatchExpressionsItem.
type SGDbOpsSpecSchedulingPodAntiAffinityPreferredDuringSchedulingIgnoredDuringExecutionItemPodAffinityTermNamespaceSelectorMatchExpressionsItem struct {
	// key is the label key that the selector applies to.
	Key string `json:"key"`

	// operator represents a key's relationship to a set of values. Valid operators are In, NotIn, Exists and DoesNotExist.
	Operator string `json:"operator"`

	// values is an array of string values. If the operator is In or NotIn, the values array must be non-empty. If the operator is Exists or DoesNotExist, the values array must be empty. This array is replaced during a strategic merge patch.
	Values *[]string `json:"values,omitempty"`
}

// SGDbOpsSpecSchedulingPodAntiAffinityRequiredDuringSchedulingIgnoredDuringExecutionItem defines model for SGDbOpsSpecSchedulingPodAntiAffinityRequiredDuringSchedulingIgnoredDuringExecutionItem.
type SGDbOpsSpecSchedulingPodAntiAffinityRequiredDuringSchedulingIgnoredDuringExecutionItem struct {
	// A label selector is a label query over a set of resources. The result of matchLabels and matchExpressions are ANDed. An empty label selector matches all objects. A null label selector matches no objects.
	LabelSelector *SGDbOpsSpecSchedulingPodAntiAffinityRequiredDuringSchedulingIgnoredDuringExecutionItemLabelSelector `json:"labelSelector,omitempty"`

	// MatchLabelKeys is a set of pod label keys to select which pods will be taken into consideration. The keys are used to lookup values from the incoming pod labels, those key-value labels are merged with `LabelSelector` as `key in (value)` to select the group of existing pods which pods will be taken into consideration for the incoming pod's pod (anti) affinity. Keys that don't exist in the incoming pod labels will be ignored. The default value is empty. The same key is forbidden to exist in both MatchLabelKeys and LabelSelector. Also, MatchLabelKeys cannot be set when LabelSelector isn't set. This is an alpha field and requires enabling MatchLabelKeysInPodAffinity feature gate.
	MatchLabelKeys *[]string `json:"matchLabelKeys,omitempty"`

	// MismatchLabelKeys is a set of pod label keys to select which pods will be taken into consideration. The keys are used to lookup values from the incoming pod labels, those key-value labels are merged with `LabelSelector` as `key notin (value)` to select the group of existing pods which pods will be taken into consideration for the incoming pod's pod (anti) affinity. Keys that don't exist in the incoming pod labels will be ignored. The default value is empty. The same key is forbidden to exist in both MismatchLabelKeys and LabelSelector. Also, MismatchLabelKeys cannot be set when LabelSelector isn't set. This is an alpha field and requires enabling MatchLabelKeysInPodAffinity feature gate.
	MismatchLabelKeys *[]string `json:"mismatchLabelKeys,omitempty"`

	// A label selector is a label query over a set of resources. The result of matchLabels and matchExpressions are ANDed. An empty label selector matches all objects. A null label selector matches no objects.
	NamespaceSelector *SGDbOpsSpecSchedulingPodAntiAffinityRequiredDuringSchedulingIgnoredDuringExecutionItemNamespaceSelector `json:"namespaceSelector,omitempty"`

	// namespaces specifies a static list of namespace names that the term applies to. The term is applied to the union of the namespaces listed in this field and the ones selected by namespaceSelector. null or empty namespaces list and null namespaceSelector means "this pod's namespace".
	Namespaces *[]string `json:"namespaces,omitempty"`

	// This pod should be co-located (affinity) or not co-located (anti-affinity) with the pods matching the labelSelector in the specified namespaces, where co-located is defined as running on a node whose value of the label with key topologyKey matches that of any node on which any of the selected pods is running. Empty topologyKey is not allowed.
	TopologyKey string `json:"topologyKey"`
}

// SGDbOpsSpecSchedulingPodAntiAffinityRequiredDuringSchedulingIgnoredDuringExecutionItemLabelSelector defines model for SGDbOpsSpecSchedulingPodAntiAffinityRequiredDuringSchedulingIgnoredDuringExecutionItemLabelSelector.
type SGDbOpsSpecSchedulingPodAntiAffinityRequiredDuringSchedulingIgnoredDuringExecutionItemLabelSelector struct {
	// matchExpressions is a list of label selector requirements. The requirements are ANDed.
	MatchExpressions *[]SGDbOpsSpecSchedulingPodAntiAffinityRequiredDuringSchedulingIgnoredDuringExecutionItemLabelSelectorMatchExpressionsItem `json:"matchExpressions,omitempty"`

	// matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels map is equivalent to an element of matchExpressions, whose key field is "key", the operator is "In", and the values array contains only "value". The requirements are ANDed.
	MatchLabels map[string]string `json:"matchLabels,omitempty"`
}

// SGDbOpsSpecSchedulingPodAntiAffinityRequiredDuringSchedulingIgnoredDuringExecutionItemLabelSelectorMatchExpressionsItem defines model for SGDbOpsSpecSchedulingPodAntiAffinityRequiredDuringSchedulingIgnoredDuringExecutionItemLabelSelectorMatchExpressionsItem.
type SGDbOpsSpecSchedulingPodAntiAffinityRequiredDuringSchedulingIgnoredDuringExecutionItemLabelSelectorMatchExpressionsItem struct {
	// key is the label key that the selector applies to.
	Key string `json:"key"`

	// operator represents a key's relationship to a set of values. Valid operators are In, NotIn, Exists and DoesNotExist.
	Operator string `json:"operator"`

	// values is an array of string values. If the operator is In or NotIn, the values array must be non-empty. If the operator is Exists or DoesNotExist, the values array must be empty. This array is replaced during a strategic merge patch.
	Values *[]string `json:"values,omitempty"`
}

// SGDbOpsSpecSchedulingPodAntiAffinityRequiredDuringSchedulingIgnoredDuringExecutionItemNamespaceSelector defines model for SGDbOpsSpecSchedulingPodAntiAffinityRequiredDuringSchedulingIgnoredDuringExecutionItemNamespaceSelector.
type SGDbOpsSpecSchedulingPodAntiAffinityRequiredDuringSchedulingIgnoredDuringExecutionItemNamespaceSelector struct {
	// matchExpressions is a list of label selector requirements. The requirements are ANDed.
	MatchExpressions *[]SGDbOpsSpecSchedulingPodAntiAffinityRequiredDuringSchedulingIgnoredDuringExecutionItemNamespaceSelectorMatchExpressionsItem `json:"matchExpressions,omitempty"`

	// matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels map is equivalent to an element of matchExpressions, whose key field is "key", the operator is "In", and the values array contains only "value". The requirements are ANDed.
	MatchLabels map[string]string `json:"matchLabels,omitempty"`
}

// SGDbOpsSpecSchedulingPodAntiAffinityRequiredDuringSchedulingIgnoredDuringExecutionItemNamespaceSelectorMatchExpressionsItem defines model for SGDbOpsSpecSchedulingPodAntiAffinityRequiredDuringSchedulingIgnoredDuringExecutionItemNamespaceSelectorMatchExpressionsItem.
type SGDbOpsSpecSchedulingPodAntiAffinityRequiredDuringSchedulingIgnoredDuringExecutionItemNamespaceSelectorMatchExpressionsItem struct {
	// key is the label key that the selector applies to.
	Key string `json:"key"`

	// operator represents a key's relationship to a set of values. Valid operators are In, NotIn, Exists and DoesNotExist.
	Operator string `json:"operator"`

	// values is an array of string values. If the operator is In or NotIn, the values array must be non-empty. If the operator is Exists or DoesNotExist, the values array must be empty. This array is replaced during a strategic merge patch.
	Values *[]string `json:"values,omitempty"`
}

// SGDbOpsSpecSchedulingTolerationsItem defines model for SGDbOpsSpecSchedulingTolerationsItem.
type SGDbOpsSpecSchedulingTolerationsItem struct {
	// Effect indicates the taint effect to match. Empty means match all taint effects. When specified, allowed values are NoSchedule, PreferNoSchedule and NoExecute.
	Effect *string `json:"effect,omitempty"`

	// Key is the taint key that the toleration applies to. Empty means match all taint keys. If the key is empty, operator must be Exists; this combination means to match all values and all keys.
	Key *string `json:"key,omitempty"`

	// Operator represents a key's relationship to the value. Valid operators are Exists and Equal. Defaults to Equal. Exists is equivalent to wildcard for value, so that a pod can tolerate all taints of a particular category.
	Operator *string `json:"operator,omitempty"`

	// TolerationSeconds represents the period of time the toleration (which must be of effect NoExecute, otherwise this field is ignored) tolerates the taint. By default, it is not set, which means tolerate the taint forever (do not evict). Zero and negative values will be treated as 0 (evict immediately) by the system.
	TolerationSeconds *int64 `json:"tolerationSeconds,omitempty"`

	// Value is the taint value the toleration matches to. If the operator is Exists, the value should be empty, otherwise just a regular string.
	Value *string `json:"value,omitempty"`
}

// SGDbOpsSpecSecurityUpgrade defines model for SGDbOpsSpecSecurityUpgrade.
type SGDbOpsSpecSecurityUpgrade struct {
	// The method used to perform the security upgrade operation. Available methods are:
	//
	// * `InPlace`: the in-place method does not require more resources than those that are available.
	//   In case only an instance of the StackGres cluster is present this mean the service disruption will
	//   last longer so we encourage use the reduced impact restart and especially for a production environment.
	// * `ReducedImpact`: this procedure is the same as the in-place method but require additional
	//   resources in order to spawn a new updated replica that will be removed when the procedure completes.
	Method *string `json:"method,omitempty"`
}

// SGDbOpsSpecVacuum defines model for SGDbOpsSpecVacuum.
type SGDbOpsSpecVacuum struct {
	// If true, updates statistics used by the planner to determine the most efficient way to execute a query. Defaults to: `true`.
	Analyze *bool `json:"analyze,omitempty"`

	// List of databases to vacuum or repack, don't specify to select all databases
	Databases *[]SGDbOpsSpecVacuumDatabasesItem `json:"databases,omitempty"`

	// Normally, VACUUM will skip pages based on the visibility map. Pages where all tuples are known to be frozen can always be
	//   skipped, and those where all tuples are known to be visible to all transactions may be skipped except when performing an
	//   aggressive vacuum. Furthermore, except when performing an aggressive vacuum, some pages may be skipped in order to avoid
	//   waiting for other sessions to finish using them. This option disables all page-skipping behavior, and is intended to be
	//   used only when the contents of the visibility map are suspect, which should happen only if there is a hardware or
	//   software issue causing database corruption. Defaults to: `false`.
	DisablePageSkipping *bool `json:"disablePageSkipping,omitempty"`

	// If true selects aggressive "freezing" of tuples. Specifying FREEZE is equivalent to performing VACUUM with the
	//   vacuum_freeze_min_age and vacuum_freeze_table_age parameters set to zero. Aggressive freezing is always performed
	//   when the table is rewritten, so this option is redundant when FULL is specified. Defaults to: `false`.
	Freeze *bool `json:"freeze,omitempty"`

	// If true selects "full" vacuum, which can reclaim more space, but takes much longer and exclusively locks the table.
	// This method also requires extra disk space, since it writes a new copy of the table and doesn't release the old copy
	//   until the operation is complete. Usually this should only be used when a significant amount of space needs to be
	//   reclaimed from within the table. Defaults to: `false`.
	Full *bool `json:"full,omitempty"`
}

// SGDbOpsSpecVacuumDatabasesItem defines model for SGDbOpsSpecVacuumDatabasesItem.
type SGDbOpsSpecVacuumDatabasesItem struct {
	// If true, updates statistics used by the planner to determine the most efficient way to execute a query. Defaults to: `true`.
	Analyze *bool `json:"analyze,omitempty"`

	// Normally, VACUUM will skip pages based on the visibility map. Pages where all tuples are known to be frozen can always be
	//   skipped, and those where all tuples are known to be visible to all transactions may be skipped except when performing an
	//   aggressive vacuum. Furthermore, except when performing an aggressive vacuum, some pages may be skipped in order to avoid
	//   waiting for other sessions to finish using them. This option disables all page-skipping behavior, and is intended to be
	//   used only when the contents of the visibility map are suspect, which should happen only if there is a hardware or
	//   software issue causing database corruption. Defaults to: `false`.
	DisablePageSkipping *bool `json:"disablePageSkipping,omitempty"`

	// If true selects aggressive "freezing" of tuples. Specifying FREEZE is equivalent to performing VACUUM with the
	//   vacuum_freeze_min_age and vacuum_freeze_table_age parameters set to zero. Aggressive freezing is always performed
	//   when the table is rewritten, so this option is redundant when FULL is specified. Defaults to: `false`.
	Freeze *bool `json:"freeze,omitempty"`

	// If true selects "full" vacuum, which can reclaim more space, but takes much longer and exclusively locks the table.
	// This method also requires extra disk space, since it writes a new copy of the table and doesn't release the old copy
	//   until the operation is complete. Usually this should only be used when a significant amount of space needs to be
	//   reclaimed from within the table. Defaults to: `false`.
	Full *bool `json:"full,omitempty"`

	// the name of the database
	Name string `json:"name"`
}

// SGDbOpsStatus defines model for SGDbOpsStatus.
type SGDbOpsStatus struct {
	// The results of the benchmark
	Benchmark *SGDbOpsStatusBenchmark `json:"benchmark,omitempty"`

	// Possible conditions are:
	//
	// * Running: to indicate when the operation is actually running
	// * Completed: to indicate when the operation has completed successfully
	// * Failed: to indicate when the operation has failed
	Conditions *[]SGDbOpsStatusConditionsItem `json:"conditions,omitempty"`

	// The results of a major version upgrade
	MajorVersionUpgrade *SGDbOpsStatusMajorVersionUpgrade `json:"majorVersionUpgrade,omitempty"`

	// The results of a minor version upgrade
	MinorVersionUpgrade *SGDbOpsStatusMinorVersionUpgrade `json:"minorVersionUpgrade,omitempty"`

	// The number of retries performed by the operation
	OpRetries *int `json:"opRetries,omitempty"`

	// The ISO 8601 timestamp of when the operation started running
	OpStarted *string `json:"opStarted,omitempty"`

	// The results of a restart
	Restart *SGDbOpsStatusRestart `json:"restart,omitempty"`

	// The results of a security upgrade
	SecurityUpgrade *SGDbOpsStatusSecurityUpgrade `json:"securityUpgrade,omitempty"`
}

// SGDbOpsStatusBenchmark defines model for SGDbOpsStatusBenchmark.
type SGDbOpsStatusBenchmark struct {
	// The results of the pgbench benchmark
	Pgbench *SGDbOpsStatusBenchmarkPgbench `json:"pgbench,omitempty"`

	// The results of the sampling benchmark
	Sampling *SGDbOpsStatusBenchmarkSampling `json:"sampling,omitempty"`
}

// SGDbOpsStatusBenchmarkPgbench defines model for SGDbOpsStatusBenchmarkPgbench.
type SGDbOpsStatusBenchmarkPgbench struct {
	// Compressed and base 64 encoded HdrHistogram
	HdrHistogram *string `json:"hdrHistogram,omitempty"`

	// The latency results of the pgbench benchmark
	Latency *SGDbOpsStatusBenchmarkPgbenchLatency `json:"latency,omitempty"`

	// The scale factor used to run pgbench (`--scale`).
	ScaleFactor *float32 `json:"scaleFactor"`

	// Average per-statement latency (execution time from the perspective of the client) of each command after the benchmark finishes
	Statements *[]SGDbOpsStatusBenchmarkPgbenchStatementsItem `json:"statements,omitempty"`

	// All the transactions per second results of the pgbench benchmark
	TransactionsPerSecond *SGDbOpsStatusBenchmarkPgbenchTransactionsPerSecond `json:"transactionsPerSecond,omitempty"`

	// The number of transactions processed.
	TransactionsProcessed *int `json:"transactionsProcessed"`
}

// SGDbOpsStatusBenchmarkPgbenchLatency defines model for SGDbOpsStatusBenchmarkPgbenchLatency.
type SGDbOpsStatusBenchmarkPgbenchLatency struct {
	// Average latency of transactions
	Average *SGDbOpsStatusBenchmarkPgbenchLatencyAverage `json:"average,omitempty"`

	// The latency standard deviation of transactions.
	StandardDeviation *SGDbOpsStatusBenchmarkPgbenchLatencyStandardDeviation `json:"standardDeviation,omitempty"`
}

// SGDbOpsStatusBenchmarkPgbenchLatencyAverage defines model for SGDbOpsStatusBenchmarkPgbenchLatencyAverage.
type SGDbOpsStatusBenchmarkPgbenchLatencyAverage struct {
	// The latency measure unit
	Unit *string `json:"unit,omitempty"`

	// The latency average value
	Value *float32 `json:"value"`
}

// SGDbOpsStatusBenchmarkPgbenchLatencyStandardDeviation defines model for SGDbOpsStatusBenchmarkPgbenchLatencyStandardDeviation.
type SGDbOpsStatusBenchmarkPgbenchLatencyStandardDeviation struct {
	// The latency measure unit
	Unit *string `json:"unit,omitempty"`

	// The latency standard deviation value
	Value *float32 `json:"value"`
}

// SGDbOpsStatusBenchmarkPgbenchStatementsItem defines model for SGDbOpsStatusBenchmarkPgbenchStatementsItem.
type SGDbOpsStatusBenchmarkPgbenchStatementsItem struct {
	// The command
	Command *string `json:"command,omitempty"`

	// Average latency of the command
	Latency *float32 `json:"latency,omitempty"`

	// The script index (`0` if no custom scripts have been defined)
	Script *int `json:"script,omitempty"`

	// The average latency measure unit
	Unit *string `json:"unit,omitempty"`
}

// SGDbOpsStatusBenchmarkPgbenchTransactionsPerSecond defines model for SGDbOpsStatusBenchmarkPgbenchTransactionsPerSecond.
type SGDbOpsStatusBenchmarkPgbenchTransactionsPerSecond struct {
	// Number of Transactions Per Second (tps) excluding connection establishing.
	ExcludingConnectionsEstablishing *SGDbOpsStatusBenchmarkPgbenchTransactionsPerSecondExcludingConnectionsEstablishing `json:"excludingConnectionsEstablishing,omitempty"`

	// Number of Transactions Per Second (tps) including connection establishing.
	IncludingConnectionsEstablishing *SGDbOpsStatusBenchmarkPgbenchTransactionsPerSecondIncludingConnectionsEstablishing `json:"includingConnectionsEstablishing,omitempty"`

	// The Transactions Per Second (tps) values aggregated over unit of time
	OverTime *SGDbOpsStatusBenchmarkPgbenchTransactionsPerSecondOverTime `json:"overTime,omitempty"`
}

// SGDbOpsStatusBenchmarkPgbenchTransactionsPerSecondExcludingConnectionsEstablishing defines model for SGDbOpsStatusBenchmarkPgbenchTransactionsPerSecondExcludingConnectionsEstablishing.
type SGDbOpsStatusBenchmarkPgbenchTransactionsPerSecondExcludingConnectionsEstablishing struct {
	// Transactions Per Second (tps) measure unit
	Unit *string `json:"unit,omitempty"`

	// The Transactions Per Second (tps) excluding connections establishing value
	Value *float32 `json:"value"`
}

// SGDbOpsStatusBenchmarkPgbenchTransactionsPerSecondIncludingConnectionsEstablishing defines model for SGDbOpsStatusBenchmarkPgbenchTransactionsPerSecondIncludingConnectionsEstablishing.
type SGDbOpsStatusBenchmarkPgbenchTransactionsPerSecondIncludingConnectionsEstablishing struct {
	// Transactions Per Second (tps) measure unit
	Unit *string `json:"unit,omitempty"`

	// The Transactions Per Second (tps) including connections establishing value
	Value *float32 `json:"value,omitempty"`
}

// SGDbOpsStatusBenchmarkPgbenchTransactionsPerSecondOverTime defines model for SGDbOpsStatusBenchmarkPgbenchTransactionsPerSecondOverTime.
type SGDbOpsStatusBenchmarkPgbenchTransactionsPerSecondOverTime struct {
	// The interval duration used to aggregate the transactions per second.
	IntervalDuration *float32 `json:"intervalDuration,omitempty"`

	// The interval duration measure unit
	IntervalDurationUnit *string `json:"intervalDurationUnit,omitempty"`

	// The Transactions Per Second (tps) values aggregated over unit of time
	Values *[]float32 `json:"values,omitempty"`

	// The Transactions Per Second (tps) measures unit
	ValuesUnit *string `json:"valuesUnit,omitempty"`
}

// SGDbOpsStatusBenchmarkSampling defines model for SGDbOpsStatusBenchmarkSampling.
type SGDbOpsStatusBenchmarkSampling struct {
	// The queries sampled.
	Queries *[]SGDbOpsStatusBenchmarkSamplingQueriesItem `json:"queries,omitempty"`

	// The top queries sampled with the stats from pg_stat_statements. If is omitted if `omitTopQueriesInStatus` is set to `true`.
	TopQueries *[]SGDbOpsStatusBenchmarkSamplingTopQueriesItem `json:"topQueries,omitempty"`
}

// SGDbOpsStatusBenchmarkSamplingQueriesItem defines model for SGDbOpsStatusBenchmarkSamplingQueriesItem.
type SGDbOpsStatusBenchmarkSamplingQueriesItem struct {
	// The query id of the representative statement calculated by Postgres
	Id *string `json:"id,omitempty"`

	// A sampled SQL query
	Query *string `json:"query,omitempty"`

	// The sampled query timestamp
	Timestamp *string `json:"timestamp,omitempty"`
}

// SGDbOpsStatusBenchmarkSamplingTopQueriesItem defines model for SGDbOpsStatusBenchmarkSamplingTopQueriesItem.
type SGDbOpsStatusBenchmarkSamplingTopQueriesItem struct {
	// The query id of the representative statement calculated by Postgres
	Id *string `json:"id,omitempty"`

	// stats collected by the top queries query
	Stats map[string]string `json:"stats,omitempty"`
}

// SGDbOpsStatusConditionsItem defines model for SGDbOpsStatusConditionsItem.
type SGDbOpsStatusConditionsItem struct {
	// Last time the condition transitioned from one status to another.
	LastTransitionTime *string `json:"lastTransitionTime,omitempty"`

	// A human-readable message indicating details about the transition.
	Message *string `json:"message,omitempty"`

	// The reason for the condition last transition.
	Reason *string `json:"reason,omitempty"`

	// Status of the condition, one of `True`, `False` or `Unknown`.
	Status *string `json:"status,omitempty"`

	// Type of deployment condition.
	Type *string `json:"type,omitempty"`
}

// SGDbOpsStatusMajorVersionUpgrade defines model for SGDbOpsStatusMajorVersionUpgrade.
type SGDbOpsStatusMajorVersionUpgrade struct {
	// A failure message (when available)
	Failure *string `json:"failure,omitempty"`

	// The instances present when the operation started
	InitialInstances *[]string `json:"initialInstances,omitempty"`

	// The instances that are pending to be restarted
	PendingToRestartInstances *[]string `json:"pendingToRestartInstances,omitempty"`

	// The phase the operation is or was executing)
	Phase *string `json:"phase,omitempty"`

	// The primary instance when the operation started
	PrimaryInstance *string `json:"primaryInstance,omitempty"`

	// The instances that have been restarted
	RestartedInstances *[]string `json:"restartedInstances,omitempty"`

	// The postgres version currently used by the primary instance
	SourcePostgresVersion *string `json:"sourcePostgresVersion,omitempty"`

	// The postgres version that the cluster will be upgraded to
	TargetPostgresVersion *string `json:"targetPostgresVersion,omitempty"`
}

// SGDbOpsStatusMinorVersionUpgrade defines model for SGDbOpsStatusMinorVersionUpgrade.
type SGDbOpsStatusMinorVersionUpgrade struct {
	// A failure message (when available)
	Failure *string `json:"failure,omitempty"`

	// The instances present when the operation started
	InitialInstances *[]string `json:"initialInstances,omitempty"`

	// The instances that are pending to be restarted
	PendingToRestartInstances *[]string `json:"pendingToRestartInstances,omitempty"`

	// The primary instance when the operation started
	PrimaryInstance *string `json:"primaryInstance,omitempty"`

	// The instances that have been restarted
	RestartedInstances *[]string `json:"restartedInstances,omitempty"`

	// The postgres version currently used by the primary instance
	SourcePostgresVersion *string `json:"sourcePostgresVersion,omitempty"`

	// An ISO 8601 date indicating if and when the switchover finalized
	SwitchoverFinalized *string `json:"switchoverFinalized,omitempty"`

	// An ISO 8601 date indicating if and when the switchover initiated
	SwitchoverInitiated *string `json:"switchoverInitiated,omitempty"`

	// The postgres version that the cluster will be upgraded (or downgraded) to
	TargetPostgresVersion *string `json:"targetPostgresVersion,omitempty"`
}

// SGDbOpsStatusRestart defines model for SGDbOpsStatusRestart.
type SGDbOpsStatusRestart struct {
	// A failure message (when available)
	Failure *string `json:"failure,omitempty"`

	// The instances present when the operation started
	InitialInstances *[]string `json:"initialInstances,omitempty"`

	// The instances that are pending to be restarted
	PendingToRestartInstances *[]string `json:"pendingToRestartInstances,omitempty"`

	// The primary instance when the operation started
	PrimaryInstance *string `json:"primaryInstance,omitempty"`

	// The instances that have been restarted
	RestartedInstances *[]string `json:"restartedInstances,omitempty"`

	// An ISO 8601 date indicating if and when the switchover finalized
	SwitchoverFinalized *string `json:"switchoverFinalized,omitempty"`

	// An ISO 8601 date indicating if and when the switchover initiated
	SwitchoverInitiated *string `json:"switchoverInitiated,omitempty"`
}

// SGDbOpsStatusSecurityUpgrade defines model for SGDbOpsStatusSecurityUpgrade.
type SGDbOpsStatusSecurityUpgrade struct {
	// A failure message (when available)
	Failure *string `json:"failure,omitempty"`

	// The instances present when the operation started
	InitialInstances *[]string `json:"initialInstances,omitempty"`

	// The instances that are pending to be restarted
	PendingToRestartInstances *[]string `json:"pendingToRestartInstances,omitempty"`

	// The primary instance when the operation started
	PrimaryInstance *string `json:"primaryInstance,omitempty"`

	// The instances that have been restarted
	RestartedInstances *[]string `json:"restartedInstances,omitempty"`

	// An ISO 8601 date indicating if and when the switchover finalized
	SwitchoverFinalized *string `json:"switchoverFinalized,omitempty"`

	// An ISO 8601 date indicating if and when the switchover initiated
	SwitchoverInitiated *string `json:"switchoverInitiated,omitempty"`
}
