// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: .work/tmp/github.com/vshn/appcat/v4/apis/appcat/v1/generated.proto

package v1

import (
	fmt "fmt"

	io "io"

	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_sortkeys "github.com/gogo/protobuf/sortkeys"
	runtime "k8s.io/apimachinery/pkg/runtime"

	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

func (m *AppCat) Reset()      { *m = AppCat{} }
func (*AppCat) ProtoMessage() {}
func (*AppCat) Descriptor() ([]byte, []int) {
	return fileDescriptor_7745f0f2a1a993fe, []int{0}
}
func (m *AppCat) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AppCat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *AppCat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppCat.Merge(m, src)
}
func (m *AppCat) XXX_Size() int {
	return m.Size()
}
func (m *AppCat) XXX_DiscardUnknown() {
	xxx_messageInfo_AppCat.DiscardUnknown(m)
}

var xxx_messageInfo_AppCat proto.InternalMessageInfo

func (m *AppCatList) Reset()      { *m = AppCatList{} }
func (*AppCatList) ProtoMessage() {}
func (*AppCatList) Descriptor() ([]byte, []int) {
	return fileDescriptor_7745f0f2a1a993fe, []int{1}
}
func (m *AppCatList) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AppCatList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *AppCatList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppCatList.Merge(m, src)
}
func (m *AppCatList) XXX_Size() int {
	return m.Size()
}
func (m *AppCatList) XXX_DiscardUnknown() {
	xxx_messageInfo_AppCatList.DiscardUnknown(m)
}

var xxx_messageInfo_AppCatList proto.InternalMessageInfo

func (m *AppCatStatus) Reset()      { *m = AppCatStatus{} }
func (*AppCatStatus) ProtoMessage() {}
func (*AppCatStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_7745f0f2a1a993fe, []int{2}
}
func (m *AppCatStatus) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AppCatStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *AppCatStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppCatStatus.Merge(m, src)
}
func (m *AppCatStatus) XXX_Size() int {
	return m.Size()
}
func (m *AppCatStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_AppCatStatus.DiscardUnknown(m)
}

var xxx_messageInfo_AppCatStatus proto.InternalMessageInfo

func (m *SGBackupInfo) Reset()      { *m = SGBackupInfo{} }
func (*SGBackupInfo) ProtoMessage() {}
func (*SGBackupInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_7745f0f2a1a993fe, []int{3}
}
func (m *SGBackupInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SGBackupInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *SGBackupInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SGBackupInfo.Merge(m, src)
}
func (m *SGBackupInfo) XXX_Size() int {
	return m.Size()
}
func (m *SGBackupInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SGBackupInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SGBackupInfo proto.InternalMessageInfo

func (m *VSHNPlan) Reset()      { *m = VSHNPlan{} }
func (*VSHNPlan) ProtoMessage() {}
func (*VSHNPlan) Descriptor() ([]byte, []int) {
	return fileDescriptor_7745f0f2a1a993fe, []int{4}
}
func (m *VSHNPlan) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VSHNPlan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *VSHNPlan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VSHNPlan.Merge(m, src)
}
func (m *VSHNPlan) XXX_Size() int {
	return m.Size()
}
func (m *VSHNPlan) XXX_DiscardUnknown() {
	xxx_messageInfo_VSHNPlan.DiscardUnknown(m)
}

var xxx_messageInfo_VSHNPlan proto.InternalMessageInfo

func (m *VSHNPostgresBackup) Reset()      { *m = VSHNPostgresBackup{} }
func (*VSHNPostgresBackup) ProtoMessage() {}
func (*VSHNPostgresBackup) Descriptor() ([]byte, []int) {
	return fileDescriptor_7745f0f2a1a993fe, []int{5}
}
func (m *VSHNPostgresBackup) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VSHNPostgresBackup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *VSHNPostgresBackup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VSHNPostgresBackup.Merge(m, src)
}
func (m *VSHNPostgresBackup) XXX_Size() int {
	return m.Size()
}
func (m *VSHNPostgresBackup) XXX_DiscardUnknown() {
	xxx_messageInfo_VSHNPostgresBackup.DiscardUnknown(m)
}

var xxx_messageInfo_VSHNPostgresBackup proto.InternalMessageInfo

func (m *VSHNPostgresBackupList) Reset()      { *m = VSHNPostgresBackupList{} }
func (*VSHNPostgresBackupList) ProtoMessage() {}
func (*VSHNPostgresBackupList) Descriptor() ([]byte, []int) {
	return fileDescriptor_7745f0f2a1a993fe, []int{6}
}
func (m *VSHNPostgresBackupList) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VSHNPostgresBackupList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *VSHNPostgresBackupList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VSHNPostgresBackupList.Merge(m, src)
}
func (m *VSHNPostgresBackupList) XXX_Size() int {
	return m.Size()
}
func (m *VSHNPostgresBackupList) XXX_DiscardUnknown() {
	xxx_messageInfo_VSHNPostgresBackupList.DiscardUnknown(m)
}

var xxx_messageInfo_VSHNPostgresBackupList proto.InternalMessageInfo

func (m *VSHNPostgresBackupStatus) Reset()      { *m = VSHNPostgresBackupStatus{} }
func (*VSHNPostgresBackupStatus) ProtoMessage() {}
func (*VSHNPostgresBackupStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_7745f0f2a1a993fe, []int{7}
}
func (m *VSHNPostgresBackupStatus) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VSHNPostgresBackupStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *VSHNPostgresBackupStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VSHNPostgresBackupStatus.Merge(m, src)
}
func (m *VSHNPostgresBackupStatus) XXX_Size() int {
	return m.Size()
}
func (m *VSHNPostgresBackupStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_VSHNPostgresBackupStatus.DiscardUnknown(m)
}

var xxx_messageInfo_VSHNPostgresBackupStatus proto.InternalMessageInfo

func (m *VSHNRedisBackup) Reset()      { *m = VSHNRedisBackup{} }
func (*VSHNRedisBackup) ProtoMessage() {}
func (*VSHNRedisBackup) Descriptor() ([]byte, []int) {
	return fileDescriptor_7745f0f2a1a993fe, []int{8}
}
func (m *VSHNRedisBackup) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VSHNRedisBackup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *VSHNRedisBackup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VSHNRedisBackup.Merge(m, src)
}
func (m *VSHNRedisBackup) XXX_Size() int {
	return m.Size()
}
func (m *VSHNRedisBackup) XXX_DiscardUnknown() {
	xxx_messageInfo_VSHNRedisBackup.DiscardUnknown(m)
}

var xxx_messageInfo_VSHNRedisBackup proto.InternalMessageInfo

func (m *VSHNRedisBackupList) Reset()      { *m = VSHNRedisBackupList{} }
func (*VSHNRedisBackupList) ProtoMessage() {}
func (*VSHNRedisBackupList) Descriptor() ([]byte, []int) {
	return fileDescriptor_7745f0f2a1a993fe, []int{9}
}
func (m *VSHNRedisBackupList) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VSHNRedisBackupList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *VSHNRedisBackupList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VSHNRedisBackupList.Merge(m, src)
}
func (m *VSHNRedisBackupList) XXX_Size() int {
	return m.Size()
}
func (m *VSHNRedisBackupList) XXX_DiscardUnknown() {
	xxx_messageInfo_VSHNRedisBackupList.DiscardUnknown(m)
}

var xxx_messageInfo_VSHNRedisBackupList proto.InternalMessageInfo

func (m *VSHNRedisBackupStatus) Reset()      { *m = VSHNRedisBackupStatus{} }
func (*VSHNRedisBackupStatus) ProtoMessage() {}
func (*VSHNRedisBackupStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_7745f0f2a1a993fe, []int{10}
}
func (m *VSHNRedisBackupStatus) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VSHNRedisBackupStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *VSHNRedisBackupStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VSHNRedisBackupStatus.Merge(m, src)
}
func (m *VSHNRedisBackupStatus) XXX_Size() int {
	return m.Size()
}
func (m *VSHNRedisBackupStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_VSHNRedisBackupStatus.DiscardUnknown(m)
}

var xxx_messageInfo_VSHNRedisBackupStatus proto.InternalMessageInfo

func (m *VSHNSize) Reset()      { *m = VSHNSize{} }
func (*VSHNSize) ProtoMessage() {}
func (*VSHNSize) Descriptor() ([]byte, []int) {
	return fileDescriptor_7745f0f2a1a993fe, []int{11}
}
func (m *VSHNSize) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VSHNSize) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *VSHNSize) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VSHNSize.Merge(m, src)
}
func (m *VSHNSize) XXX_Size() int {
	return m.Size()
}
func (m *VSHNSize) XXX_DiscardUnknown() {
	xxx_messageInfo_VSHNSize.DiscardUnknown(m)
}

var xxx_messageInfo_VSHNSize proto.InternalMessageInfo

func init() {
	proto.RegisterType((*AppCat)(nil), "github.com.vshn.appcat.v4.apis.appcat.v1.AppCat")
	proto.RegisterMapType((Details)(nil), "github.com.vshn.appcat.v4.apis.appcat.v1.AppCat.DetailsEntry")
	proto.RegisterMapType((map[string]VSHNPlan)(nil), "github.com.vshn.appcat.v4.apis.appcat.v1.AppCat.PlansEntry")
	proto.RegisterType((*AppCatList)(nil), "github.com.vshn.appcat.v4.apis.appcat.v1.AppCatList")
	proto.RegisterType((*AppCatStatus)(nil), "github.com.vshn.appcat.v4.apis.appcat.v1.AppCatStatus")
	proto.RegisterType((*SGBackupInfo)(nil), "github.com.vshn.appcat.v4.apis.appcat.v1.SGBackupInfo")
	proto.RegisterType((*VSHNPlan)(nil), "github.com.vshn.appcat.v4.apis.appcat.v1.VSHNPlan")
	proto.RegisterType((*VSHNPostgresBackup)(nil), "github.com.vshn.appcat.v4.apis.appcat.v1.VSHNPostgresBackup")
	proto.RegisterType((*VSHNPostgresBackupList)(nil), "github.com.vshn.appcat.v4.apis.appcat.v1.VSHNPostgresBackupList")
	proto.RegisterType((*VSHNPostgresBackupStatus)(nil), "github.com.vshn.appcat.v4.apis.appcat.v1.VSHNPostgresBackupStatus")
	proto.RegisterType((*VSHNRedisBackup)(nil), "github.com.vshn.appcat.v4.apis.appcat.v1.VSHNRedisBackup")
	proto.RegisterType((*VSHNRedisBackupList)(nil), "github.com.vshn.appcat.v4.apis.appcat.v1.VSHNRedisBackupList")
	proto.RegisterType((*VSHNRedisBackupStatus)(nil), "github.com.vshn.appcat.v4.apis.appcat.v1.VSHNRedisBackupStatus")
	proto.RegisterType((*VSHNSize)(nil), "github.com.vshn.appcat.v4.apis.appcat.v1.VSHNSize")
}

func init() {
	proto.RegisterFile(".work/tmp/github.com/vshn/appcat/v4/apis/appcat/v1/generated.proto", fileDescriptor_7745f0f2a1a993fe)
}

var fileDescriptor_7745f0f2a1a993fe = []byte{
	// 951 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x57, 0xdd, 0x6e, 0x1b, 0x45,
	0x14, 0xf6, 0xda, 0xce, 0x4f, 0x8f, 0x03, 0x49, 0x07, 0x0a, 0xc6, 0x12, 0x6e, 0xe4, 0x0b, 0x14,
	0x21, 0xba, 0xdb, 0x44, 0x51, 0x55, 0x0a, 0x08, 0x75, 0xe3, 0x8a, 0x06, 0xb5, 0x21, 0x4c, 0x1a,
	0x84, 0x10, 0xaa, 0x3a, 0xde, 0x9d, 0x3a, 0x53, 0x67, 0x77, 0x56, 0x3b, 0x63, 0x97, 0xf4, 0x0a,
	0x89, 0x17, 0xe0, 0x39, 0xb8, 0xe1, 0x19, 0xb8, 0x41, 0x91, 0xb8, 0xa9, 0xc4, 0x4d, 0x91, 0x50,
	0x45, 0xcc, 0x5b, 0x70, 0x85, 0x66, 0x67, 0xbc, 0x5e, 0xff, 0x11, 0xdb, 0x54, 0xb9, 0xdb, 0xf9,
	0xf9, 0xbe, 0xef, 0x9c, 0x33, 0xdf, 0x39, 0xb2, 0xc1, 0xb5, 0x9f, 0xf2, 0xb8, 0xe5, 0xc8, 0x20,
	0x72, 0x9a, 0x4c, 0x1e, 0xb5, 0x1b, 0xb6, 0xc7, 0x03, 0xa7, 0x23, 0x8e, 0x42, 0x87, 0x44, 0x91,
	0x47, 0xa4, 0xd3, 0xd9, 0x76, 0x48, 0xc4, 0x44, 0xba, 0xdc, 0x74, 0x9a, 0x34, 0xa4, 0x31, 0x91,
	0xd4, 0xb7, 0xa3, 0x98, 0x4b, 0x8e, 0x36, 0xfa, 0x48, 0x5b, 0x21, 0x6d, 0x7d, 0xd5, 0xee, 0x6c,
	0xdb, 0x0a, 0x99, 0x2e, 0x37, 0x2b, 0xd7, 0x32, 0x1a, 0x4d, 0xde, 0xe4, 0x4e, 0x42, 0xd0, 0x68,
	0x3f, 0x4e, 0x56, 0xc9, 0x22, 0xf9, 0xd2, 0xc4, 0x95, 0xed, 0xd6, 0x4d, 0x61, 0x33, 0xae, 0xf4,
	0x03, 0xe2, 0x1d, 0xb1, 0x90, 0xc6, 0x27, 0x4e, 0xd4, 0x6a, 0xea, 0x80, 0x02, 0x2a, 0xc9, 0x98,
	0x70, 0x2a, 0xce, 0x24, 0x54, 0xdc, 0x0e, 0x25, 0x0b, 0xe8, 0x08, 0xe0, 0xc6, 0x79, 0x00, 0xe1,
	0x1d, 0xd1, 0x80, 0x0c, 0xe3, 0x6a, 0xbf, 0x15, 0x61, 0xf1, 0x76, 0x14, 0xed, 0x10, 0x89, 0x1e,
	0xc1, 0xb2, 0x0a, 0xc7, 0x27, 0x92, 0x94, 0xad, 0x75, 0x6b, 0xa3, 0xb4, 0x75, 0xdd, 0xd6, 0xac,
	0x76, 0x96, 0xd5, 0x8e, 0x5a, 0x4d, 0x5d, 0x13, 0x75, 0xdb, 0xee, 0x6c, 0xda, 0x5f, 0x34, 0x9e,
	0x50, 0x4f, 0xde, 0xa7, 0x92, 0xb8, 0xe8, 0xf4, 0xe5, 0xd5, 0x5c, 0xf7, 0xe5, 0x55, 0xe8, 0xef,
	0xe1, 0x94, 0x15, 0x09, 0x58, 0xf2, 0xa9, 0x24, 0xec, 0x58, 0x94, 0xf3, 0xeb, 0x85, 0x8d, 0xd2,
	0xd6, 0x27, 0xf6, 0xb4, 0x65, 0xb7, 0x75, 0x90, 0x76, 0x5d, 0xe3, 0xef, 0x84, 0x32, 0x3e, 0x71,
	0x2b, 0x46, 0x6d, 0xc9, 0xec, 0xfe, 0xd3, 0xff, 0xc4, 0x3d, 0x25, 0xf4, 0x08, 0x16, 0xa2, 0x63,
	0x12, 0x8a, 0x72, 0x21, 0x91, 0xfc, 0x68, 0x66, 0xc9, 0x7d, 0x85, 0xd6, 0x82, 0xaf, 0x19, 0xc1,
	0x85, 0x64, 0x0f, 0x6b, 0x62, 0xf4, 0x10, 0x16, 0x85, 0x24, 0xb2, 0x2d, 0xca, 0xc5, 0xa4, 0x6c,
	0x37, 0x66, 0x95, 0x38, 0x48, 0xd0, 0xee, 0xeb, 0x86, 0x7d, 0x51, 0xaf, 0xb1, 0x61, 0xad, 0xdc,
	0x82, 0x95, 0x6c, 0xda, 0x68, 0x0d, 0x0a, 0x2d, 0x7a, 0x92, 0xbc, 0xd1, 0x25, 0xac, 0x3e, 0xd1,
	0x9b, 0xb0, 0xd0, 0x21, 0xc7, 0x6d, 0x5a, 0xce, 0x27, 0x7b, 0x7a, 0x71, 0x2b, 0x7f, 0xd3, 0xaa,
	0x1c, 0x03, 0xf4, 0xe3, 0x1f, 0x83, 0xbc, 0x9b, 0x45, 0x96, 0xb6, 0xb6, 0xa6, 0x0f, 0xfd, 0xab,
	0x83, 0xbb, 0x7b, 0x8a, 0x3a, 0xa3, 0x56, 0xfb, 0xc5, 0x02, 0xd0, 0x29, 0xdd, 0x63, 0x42, 0xa2,
	0x6f, 0x47, 0x1c, 0x65, 0x4f, 0xe7, 0x28, 0x85, 0x4e, 0xfc, 0xb4, 0x66, 0x4a, 0xb2, 0xdc, 0xdb,
	0xc9, 0xb8, 0xe9, 0x10, 0x16, 0x98, 0xa4, 0x41, 0xcf, 0x4b, 0xd7, 0x67, 0xad, 0x7a, 0xff, 0x35,
	0x77, 0x15, 0x0d, 0xd6, 0x6c, 0xb5, 0x2f, 0x61, 0x25, 0xfb, 0x2a, 0xe8, 0x36, 0xac, 0x7a, 0x3c,
	0x88, 0xb8, 0x60, 0x92, 0xf1, 0x70, 0x8f, 0x04, 0x54, 0xd7, 0xcf, 0x7d, 0xdb, 0xc0, 0x57, 0x77,
	0x06, 0x8f, 0xf1, 0xf0, 0xfd, 0xda, 0xaf, 0x79, 0x58, 0x39, 0xf8, 0xcc, 0x25, 0x5e, 0xab, 0x1d,
	0xed, 0x86, 0x8f, 0x39, 0xf2, 0x01, 0x78, 0xda, 0x20, 0xaf, 0xb4, 0xd9, 0x32, 0xbc, 0xe8, 0x6b,
	0x58, 0x8a, 0x62, 0xee, 0x51, 0x21, 0xcc, 0xeb, 0x5e, 0x9b, 0x28, 0x61, 0xa6, 0x84, 0x8d, 0xc9,
	0xd3, 0x3b, 0xdf, 0x49, 0x1a, 0x0a, 0xc6, 0x43, 0x77, 0xb5, 0xd7, 0x5e, 0xfb, 0x9a, 0x05, 0xf7,
	0xe8, 0x50, 0x07, 0x2e, 0x37, 0xd2, 0x6c, 0xe2, 0x80, 0xa8, 0x4c, 0xcb, 0x85, 0x79, 0x34, 0xde,
	0x31, 0x1a, 0x97, 0xdd, 0x61, 0x3e, 0x3c, 0x2a, 0x51, 0xfb, 0xc1, 0x82, 0xe5, 0x9e, 0xef, 0xd0,
	0x3a, 0x14, 0x43, 0x2e, 0x7b, 0xaf, 0xb1, 0x62, 0x88, 0x8a, 0x7b, 0x5c, 0x52, 0x9c, 0x9c, 0xa0,
	0x43, 0x28, 0x0a, 0xf6, 0x6c, 0x4e, 0x6f, 0x1f, 0xb0, 0x67, 0xb4, 0x6f, 0x91, 0xcf, 0xd5, 0x12,
	0x27, 0x74, 0xb5, 0xae, 0x05, 0x28, 0x89, 0x82, 0x0b, 0xd9, 0x8c, 0xa9, 0xd0, 0xa1, 0x5f, 0xc0,
	0xfc, 0x7c, 0x92, 0x0e, 0x1a, 0x9d, 0x91, 0x3b, 0x63, 0xb7, 0x0e, 0xc4, 0xfb, 0xdf, 0x43, 0xa7,
	0xf6, 0x87, 0x05, 0x6f, 0x8d, 0x82, 0x2e, 0xa0, 0xad, 0xc9, 0x60, 0x5b, 0x7f, 0xfc, 0x7f, 0x72,
	0x9c, 0xd0, 0xe2, 0x3f, 0xe5, 0xa1, 0x3c, 0xa9, 0x20, 0xe8, 0x41, 0xbf, 0x6b, 0xac, 0x79, 0x1c,
	0x5d, 0x1a, 0xdb, 0x31, 0xf1, 0xb8, 0x8e, 0x99, 0xab, 0x2b, 0xaf, 0x4c, 0xdb, 0x2d, 0xa8, 0x0e,
	0x6b, 0xaa, 0xa2, 0x0d, 0x22, 0xe8, 0x6e, 0x28, 0x24, 0x09, 0x3d, 0x9a, 0x34, 0xe9, 0x25, 0xb7,
	0x6c, 0xca, 0xb2, 0x56, 0x1f, 0x3a, 0xc7, 0x23, 0x88, 0xda, 0x9f, 0x16, 0xac, 0xaa, 0x62, 0x61,
	0xea, 0xb3, 0x8b, 0xb3, 0x7a, 0x73, 0xc8, 0xea, 0x9f, 0xce, 0x66, 0x83, 0x4c, 0xb0, 0xe7, 0xf8,
	0xfc, 0x77, 0x0b, 0xde, 0x18, 0x42, 0x5c, 0x80, 0xc9, 0x1f, 0x0e, 0x9a, 0xfc, 0xc3, 0xb9, 0xb3,
	0x9b, 0xe0, 0xf0, 0x9f, 0x2d, 0xb8, 0x32, 0xb6, 0x0e, 0xa8, 0x02, 0x79, 0xe6, 0x9b, 0x99, 0x09,
	0x06, 0x9b, 0xdf, 0xad, 0xe3, 0x3c, 0xf3, 0xd1, 0x3d, 0x28, 0xfa, 0x44, 0xf6, 0xe6, 0xe5, 0xfb,
	0xd3, 0xe5, 0xfb, 0x80, 0x05, 0xb4, 0x3f, 0x7d, 0xeb, 0x44, 0x4d, 0x5f, 0xc5, 0x82, 0x3e, 0x80,
	0x65, 0x36, 0x68, 0xbb, 0xb4, 0x22, 0xa9, 0xdd, 0xd2, 0x1b, 0x35, 0xa1, 0x27, 0xbb, 0x1a, 0xb3,
	0xe8, 0x5d, 0x28, 0x78, 0x51, 0xdb, 0x04, 0x59, 0x32, 0xa0, 0xc2, 0xce, 0xfe, 0x21, 0x56, 0xfb,
	0x6a, 0xf0, 0xfb, 0x4c, 0xb4, 0xf4, 0x8f, 0x9d, 0x8c, 0x34, 0x13, 0x2d, 0x9c, 0x9c, 0xa0, 0xf7,
	0x60, 0x31, 0xa0, 0x01, 0x8f, 0x4f, 0x8c, 0x70, 0xfa, 0xf8, 0xf7, 0x93, 0x5d, 0x6c, 0x4e, 0xdd,
	0xbd, 0xd3, 0xb3, 0x6a, 0xee, 0xf9, 0x59, 0x35, 0xf7, 0xe2, 0xac, 0x9a, 0xfb, 0xbe, 0x5b, 0xb5,
	0x4e, 0xbb, 0x55, 0xeb, 0x79, 0xb7, 0x6a, 0xbd, 0xe8, 0x56, 0xad, 0xbf, 0xba, 0x55, 0xeb, 0xc7,
	0xbf, 0xab, 0xb9, 0x6f, 0x36, 0xa6, 0xfd, 0x57, 0xf1, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x48,
	0x35, 0x98, 0x68, 0x8a, 0x0c, 0x00, 0x00,
}

func (m *AppCat) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AppCat) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AppCat) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Status.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.Plans) > 0 {
		keysForPlans := make([]string, 0, len(m.Plans))
		for k := range m.Plans {
			keysForPlans = append(keysForPlans, string(k))
		}
		github_com_gogo_protobuf_sortkeys.Strings(keysForPlans)
		for iNdEx := len(keysForPlans) - 1; iNdEx >= 0; iNdEx-- {
			v := m.Plans[string(keysForPlans[iNdEx])]
			baseI := i
			{
				size, err := (&v).MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenerated(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
			i -= len(keysForPlans[iNdEx])
			copy(dAtA[i:], keysForPlans[iNdEx])
			i = encodeVarintGenerated(dAtA, i, uint64(len(keysForPlans[iNdEx])))
			i--
			dAtA[i] = 0xa
			i = encodeVarintGenerated(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Details) > 0 {
		keysForDetails := make([]string, 0, len(m.Details))
		for k := range m.Details {
			keysForDetails = append(keysForDetails, string(k))
		}
		github_com_gogo_protobuf_sortkeys.Strings(keysForDetails)
		for iNdEx := len(keysForDetails) - 1; iNdEx >= 0; iNdEx-- {
			v := m.Details[string(keysForDetails[iNdEx])]
			baseI := i
			i -= len(v)
			copy(dAtA[i:], v)
			i = encodeVarintGenerated(dAtA, i, uint64(len(v)))
			i--
			dAtA[i] = 0x12
			i -= len(keysForDetails[iNdEx])
			copy(dAtA[i:], keysForDetails[iNdEx])
			i = encodeVarintGenerated(dAtA, i, uint64(len(keysForDetails[iNdEx])))
			i--
			dAtA[i] = 0xa
			i = encodeVarintGenerated(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.ObjectMeta.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *AppCatList) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AppCatList) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AppCatList) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Items) > 0 {
		for iNdEx := len(m.Items) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Items[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenerated(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.ListMeta.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *AppCatStatus) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AppCatStatus) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AppCatStatus) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	i -= len(m.CompositionName)
	copy(dAtA[i:], m.CompositionName)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.CompositionName)))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *SGBackupInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SGBackupInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SGBackupInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.BackupInformation.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.Process.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.ObjectMeta.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *VSHNPlan) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VSHNPlan) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VSHNPlan) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.JSize.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	i -= len(m.Note)
	copy(dAtA[i:], m.Note)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.Note)))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *VSHNPostgresBackup) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VSHNPostgresBackup) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VSHNPostgresBackup) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Status.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.ObjectMeta.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *VSHNPostgresBackupList) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VSHNPostgresBackupList) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VSHNPostgresBackupList) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Items) > 0 {
		for iNdEx := len(m.Items) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Items[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenerated(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.ListMeta.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *VSHNPostgresBackupStatus) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VSHNPostgresBackupStatus) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VSHNPostgresBackupStatus) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	i -= len(m.DatabaseInstance)
	copy(dAtA[i:], m.DatabaseInstance)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.DatabaseInstance)))
	i--
	dAtA[i] = 0x1a
	if m.BackupInformation != nil {
		{
			size, err := m.BackupInformation.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenerated(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Process != nil {
		{
			size, err := m.Process.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenerated(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *VSHNRedisBackup) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VSHNRedisBackup) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VSHNRedisBackup) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Status.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.ObjectMeta.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *VSHNRedisBackupList) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VSHNRedisBackupList) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VSHNRedisBackupList) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Items) > 0 {
		for iNdEx := len(m.Items) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Items[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenerated(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.ListMeta.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *VSHNRedisBackupStatus) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VSHNRedisBackupStatus) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VSHNRedisBackupStatus) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	i -= len(m.Instance)
	copy(dAtA[i:], m.Instance)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.Instance)))
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.Date.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	i -= len(m.ID)
	copy(dAtA[i:], m.ID)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.ID)))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *VSHNSize) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VSHNSize) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VSHNSize) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	i -= len(m.Memory)
	copy(dAtA[i:], m.Memory)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.Memory)))
	i--
	dAtA[i] = 0x1a
	i -= len(m.Disk)
	copy(dAtA[i:], m.Disk)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.Disk)))
	i--
	dAtA[i] = 0x12
	i -= len(m.CPU)
	copy(dAtA[i:], m.CPU)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.CPU)))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenerated(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenerated(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *AppCat) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ObjectMeta.Size()
	n += 1 + l + sovGenerated(uint64(l))
	if len(m.Details) > 0 {
		for k, v := range m.Details {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovGenerated(uint64(len(k))) + 1 + len(v) + sovGenerated(uint64(len(v)))
			n += mapEntrySize + 1 + sovGenerated(uint64(mapEntrySize))
		}
	}
	if len(m.Plans) > 0 {
		for k, v := range m.Plans {
			_ = k
			_ = v
			l = v.Size()
			mapEntrySize := 1 + len(k) + sovGenerated(uint64(len(k))) + 1 + l + sovGenerated(uint64(l))
			n += mapEntrySize + 1 + sovGenerated(uint64(mapEntrySize))
		}
	}
	l = m.Status.Size()
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func (m *AppCatList) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ListMeta.Size()
	n += 1 + l + sovGenerated(uint64(l))
	if len(m.Items) > 0 {
		for _, e := range m.Items {
			l = e.Size()
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	return n
}

func (m *AppCatStatus) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.CompositionName)
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func (m *SGBackupInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ObjectMeta.Size()
	n += 1 + l + sovGenerated(uint64(l))
	l = m.Process.Size()
	n += 1 + l + sovGenerated(uint64(l))
	l = m.BackupInformation.Size()
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func (m *VSHNPlan) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Note)
	n += 1 + l + sovGenerated(uint64(l))
	l = m.JSize.Size()
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func (m *VSHNPostgresBackup) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ObjectMeta.Size()
	n += 1 + l + sovGenerated(uint64(l))
	l = m.Status.Size()
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func (m *VSHNPostgresBackupList) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ListMeta.Size()
	n += 1 + l + sovGenerated(uint64(l))
	if len(m.Items) > 0 {
		for _, e := range m.Items {
			l = e.Size()
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	return n
}

func (m *VSHNPostgresBackupStatus) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Process != nil {
		l = m.Process.Size()
		n += 1 + l + sovGenerated(uint64(l))
	}
	if m.BackupInformation != nil {
		l = m.BackupInformation.Size()
		n += 1 + l + sovGenerated(uint64(l))
	}
	l = len(m.DatabaseInstance)
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func (m *VSHNRedisBackup) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ObjectMeta.Size()
	n += 1 + l + sovGenerated(uint64(l))
	l = m.Status.Size()
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func (m *VSHNRedisBackupList) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ListMeta.Size()
	n += 1 + l + sovGenerated(uint64(l))
	if len(m.Items) > 0 {
		for _, e := range m.Items {
			l = e.Size()
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	return n
}

func (m *VSHNRedisBackupStatus) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ID)
	n += 1 + l + sovGenerated(uint64(l))
	l = m.Date.Size()
	n += 1 + l + sovGenerated(uint64(l))
	l = len(m.Instance)
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func (m *VSHNSize) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.CPU)
	n += 1 + l + sovGenerated(uint64(l))
	l = len(m.Disk)
	n += 1 + l + sovGenerated(uint64(l))
	l = len(m.Memory)
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func sovGenerated(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenerated(x uint64) (n int) {
	return sovGenerated(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *AppCat) String() string {
	if this == nil {
		return "nil"
	}
	keysForDetails := make([]string, 0, len(this.Details))
	for k := range this.Details {
		keysForDetails = append(keysForDetails, k)
	}
	github_com_gogo_protobuf_sortkeys.Strings(keysForDetails)
	mapStringForDetails := "Details{"
	for _, k := range keysForDetails {
		mapStringForDetails += fmt.Sprintf("%v: %v,", k, this.Details[k])
	}
	mapStringForDetails += "}"
	keysForPlans := make([]string, 0, len(this.Plans))
	for k := range this.Plans {
		keysForPlans = append(keysForPlans, k)
	}
	github_com_gogo_protobuf_sortkeys.Strings(keysForPlans)
	mapStringForPlans := "map[string]VSHNPlan{"
	for _, k := range keysForPlans {
		mapStringForPlans += fmt.Sprintf("%v: %v,", k, this.Plans[k])
	}
	mapStringForPlans += "}"
	s := strings.Join([]string{`&AppCat{`,
		`ObjectMeta:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.ObjectMeta), "ObjectMeta", "v1.ObjectMeta", 1), `&`, ``, 1) + `,`,
		`Details:` + mapStringForDetails + `,`,
		`Plans:` + mapStringForPlans + `,`,
		`Status:` + strings.Replace(strings.Replace(this.Status.String(), "AppCatStatus", "AppCatStatus", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *AppCatList) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForItems := "[]AppCat{"
	for _, f := range this.Items {
		repeatedStringForItems += strings.Replace(strings.Replace(f.String(), "AppCat", "AppCat", 1), `&`, ``, 1) + ","
	}
	repeatedStringForItems += "}"
	s := strings.Join([]string{`&AppCatList{`,
		`ListMeta:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.ListMeta), "ListMeta", "v1.ListMeta", 1), `&`, ``, 1) + `,`,
		`Items:` + repeatedStringForItems + `,`,
		`}`,
	}, "")
	return s
}
func (this *AppCatStatus) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&AppCatStatus{`,
		`CompositionName:` + fmt.Sprintf("%v", this.CompositionName) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SGBackupInfo) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SGBackupInfo{`,
		`ObjectMeta:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.ObjectMeta), "ObjectMeta", "v1.ObjectMeta", 1), `&`, ``, 1) + `,`,
		`Process:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.Process), "RawExtension", "runtime.RawExtension", 1), `&`, ``, 1) + `,`,
		`BackupInformation:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.BackupInformation), "RawExtension", "runtime.RawExtension", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *VSHNPlan) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&VSHNPlan{`,
		`Note:` + fmt.Sprintf("%v", this.Note) + `,`,
		`JSize:` + strings.Replace(strings.Replace(this.JSize.String(), "VSHNSize", "VSHNSize", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *VSHNPostgresBackup) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&VSHNPostgresBackup{`,
		`ObjectMeta:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.ObjectMeta), "ObjectMeta", "v1.ObjectMeta", 1), `&`, ``, 1) + `,`,
		`Status:` + strings.Replace(strings.Replace(this.Status.String(), "VSHNPostgresBackupStatus", "VSHNPostgresBackupStatus", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *VSHNPostgresBackupList) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForItems := "[]VSHNPostgresBackup{"
	for _, f := range this.Items {
		repeatedStringForItems += strings.Replace(strings.Replace(f.String(), "VSHNPostgresBackup", "VSHNPostgresBackup", 1), `&`, ``, 1) + ","
	}
	repeatedStringForItems += "}"
	s := strings.Join([]string{`&VSHNPostgresBackupList{`,
		`ListMeta:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.ListMeta), "ListMeta", "v1.ListMeta", 1), `&`, ``, 1) + `,`,
		`Items:` + repeatedStringForItems + `,`,
		`}`,
	}, "")
	return s
}
func (this *VSHNPostgresBackupStatus) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&VSHNPostgresBackupStatus{`,
		`Process:` + strings.Replace(fmt.Sprintf("%v", this.Process), "RawExtension", "runtime.RawExtension", 1) + `,`,
		`BackupInformation:` + strings.Replace(fmt.Sprintf("%v", this.BackupInformation), "RawExtension", "runtime.RawExtension", 1) + `,`,
		`DatabaseInstance:` + fmt.Sprintf("%v", this.DatabaseInstance) + `,`,
		`}`,
	}, "")
	return s
}
func (this *VSHNRedisBackup) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&VSHNRedisBackup{`,
		`ObjectMeta:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.ObjectMeta), "ObjectMeta", "v1.ObjectMeta", 1), `&`, ``, 1) + `,`,
		`Status:` + strings.Replace(strings.Replace(this.Status.String(), "VSHNRedisBackupStatus", "VSHNRedisBackupStatus", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *VSHNRedisBackupList) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForItems := "[]VSHNRedisBackup{"
	for _, f := range this.Items {
		repeatedStringForItems += strings.Replace(strings.Replace(f.String(), "VSHNRedisBackup", "VSHNRedisBackup", 1), `&`, ``, 1) + ","
	}
	repeatedStringForItems += "}"
	s := strings.Join([]string{`&VSHNRedisBackupList{`,
		`ListMeta:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.ListMeta), "ListMeta", "v1.ListMeta", 1), `&`, ``, 1) + `,`,
		`Items:` + repeatedStringForItems + `,`,
		`}`,
	}, "")
	return s
}
func (this *VSHNRedisBackupStatus) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&VSHNRedisBackupStatus{`,
		`ID:` + fmt.Sprintf("%v", this.ID) + `,`,
		`Date:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.Date), "Time", "v1.Time", 1), `&`, ``, 1) + `,`,
		`Instance:` + fmt.Sprintf("%v", this.Instance) + `,`,
		`}`,
	}, "")
	return s
}
func (this *VSHNSize) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&VSHNSize{`,
		`CPU:` + fmt.Sprintf("%v", this.CPU) + `,`,
		`Disk:` + fmt.Sprintf("%v", this.Disk) + `,`,
		`Memory:` + fmt.Sprintf("%v", this.Memory) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringGenerated(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *AppCat) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AppCat: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AppCat: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObjectMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ObjectMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Details", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Details == nil {
				m.Details = make(Details)
			}
			var mapkey string
			var mapvalue string
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGenerated
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowGenerated
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthGenerated
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthGenerated
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var stringLenmapvalue uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowGenerated
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapvalue |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapvalue := int(stringLenmapvalue)
					if intStringLenmapvalue < 0 {
						return ErrInvalidLengthGenerated
					}
					postStringIndexmapvalue := iNdEx + intStringLenmapvalue
					if postStringIndexmapvalue < 0 {
						return ErrInvalidLengthGenerated
					}
					if postStringIndexmapvalue > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = string(dAtA[iNdEx:postStringIndexmapvalue])
					iNdEx = postStringIndexmapvalue
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipGenerated(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthGenerated
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Details[mapkey] = mapvalue
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Plans", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Plans == nil {
				m.Plans = make(map[string]VSHNPlan)
			}
			var mapkey string
			mapvalue := &VSHNPlan{}
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGenerated
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowGenerated
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthGenerated
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthGenerated
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var mapmsglen int
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowGenerated
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapmsglen |= int(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					if mapmsglen < 0 {
						return ErrInvalidLengthGenerated
					}
					postmsgIndex := iNdEx + mapmsglen
					if postmsgIndex < 0 {
						return ErrInvalidLengthGenerated
					}
					if postmsgIndex > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = &VSHNPlan{}
					if err := mapvalue.Unmarshal(dAtA[iNdEx:postmsgIndex]); err != nil {
						return err
					}
					iNdEx = postmsgIndex
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipGenerated(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthGenerated
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Plans[mapkey] = *mapvalue
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Status.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AppCatList) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AppCatList: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AppCatList: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ListMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ListMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Items", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Items = append(m.Items, AppCat{})
			if err := m.Items[len(m.Items)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AppCatStatus) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AppCatStatus: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AppCatStatus: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CompositionName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CompositionName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SGBackupInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SGBackupInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SGBackupInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObjectMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ObjectMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Process", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Process.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BackupInformation", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BackupInformation.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VSHNPlan) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VSHNPlan: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VSHNPlan: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Note", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Note = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field JSize", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.JSize.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VSHNPostgresBackup) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VSHNPostgresBackup: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VSHNPostgresBackup: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObjectMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ObjectMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Status.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VSHNPostgresBackupList) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VSHNPostgresBackupList: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VSHNPostgresBackupList: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ListMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ListMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Items", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Items = append(m.Items, VSHNPostgresBackup{})
			if err := m.Items[len(m.Items)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VSHNPostgresBackupStatus) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VSHNPostgresBackupStatus: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VSHNPostgresBackupStatus: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Process", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Process == nil {
				m.Process = &runtime.RawExtension{}
			}
			if err := m.Process.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BackupInformation", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.BackupInformation == nil {
				m.BackupInformation = &runtime.RawExtension{}
			}
			if err := m.BackupInformation.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DatabaseInstance", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DatabaseInstance = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VSHNRedisBackup) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VSHNRedisBackup: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VSHNRedisBackup: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObjectMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ObjectMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Status.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VSHNRedisBackupList) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VSHNRedisBackupList: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VSHNRedisBackupList: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ListMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ListMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Items", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Items = append(m.Items, VSHNRedisBackup{})
			if err := m.Items[len(m.Items)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VSHNRedisBackupStatus) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VSHNRedisBackupStatus: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VSHNRedisBackupStatus: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Date", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Date.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Instance", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Instance = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VSHNSize) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VSHNSize: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VSHNSize: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CPU", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CPU = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Disk", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Disk = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Memory", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Memory = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenerated(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenerated
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenerated
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenerated
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenerated        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenerated          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenerated = fmt.Errorf("proto: unexpected end of group")
)
