apiVersion: apps/v1
kind: Deployment
metadata:
  name: appcat-controller
  namespace: appcat-controllers
  labels:
    appcat-controller: appcat-controller
spec:
  selector:
    matchLabels:
      appcat-controller: appcat-controller
  replicas: 1
  template:
    metadata:
      labels:
        appcat-controller: appcat-controller
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - args:
            - "controller"
            - "--leader-elect"
          image: "ghcr.io/vshn/appcat:v0.0.1" #patched
          name: manager
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 20Mi
      serviceAccountName: appcat-controller
      terminationGracePeriodSeconds: 10
