openapi: "3.0.2"
paths:
  "/spec":
    get:
      responses:
        "200":
          content:
            "application/json":
              schema:
                "$ref": "#/components/schemas/ImageCatalogSpec"
components:
  schemas:
    ImageCatalogSpec:
      description: |-
        Specification of the desired behavior of the ImageCatalog.
        More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#spec-and-status
      properties:
        images:
          description: List of CatalogImages available in the catalog
          items:
            description: CatalogImage defines the image and major version
            properties:
              image:
                description: The image reference
                type: string
              major:
                description: The PostgreSQL major version of the image. Must be unique within the catalog.
                minimum: 10
                type: integer
            required:
              - image
              - major
            type: object
          maxItems: 8
          minItems: 1
          type: array
          x-kubernetes-validations:
            - message: Images must have unique major versions
              rule: self.all(e, self.filter(f, f.major==e.major).size() == 1)
      required:
        - images
      type: object
