// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.1 DO NOT EDIT.
package v1

// ImageCatalogSpec defines model for ImageCatalogSpec.
type ImageCatalogSpec struct {
	// List of CatalogImages available in the catalog
	Images []ImageCatalogSpecImagesItem `json:"images"`
}

// ImageCatalogSpecImagesItem defines model for ImageCatalogSpecImagesItem.
type ImageCatalogSpecImagesItem struct {
	// The image reference
	Image string `json:"image"`

	// The PostgreSQL major version of the image. Must be unique within the catalog.
	Major int `json:"major"`
}
