name: Diff
on:
  pull_request: {}

jobs:
  render-diff:
    runs-on: ubuntu-latest
    steps:

      - name: Wait on Workflow
        uses: lucasssvaz/wait-on-workflow@v1
        with:
          workflow: pr.yml
          max-wait: 3
          timeout: 60
          sha: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Trigger diff on internal gitlab
        run: |
          curl -X POST \
             --fail \
             -F token=${{ secrets.GITLAB_CI_TOKEN }} \
             -F ref=add/pipeline \
             -F "variables[BRANCH]=${{ steps.extract_branch.outputs.branch }}" \
             https://git.vshn.net/api/v4/projects/58084/trigger/pipeline
